In [3]:
import pandas as pd
import requests 
from bs4 import BeautifulSoup

In [12]:
requests.get('https://finance.yahoo.com/markets/stocks/most-active/?start=0&count=100')

In [13]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get('https://finance.yahoo.com/markets/stocks/most-active/?start=0&count=100',headers=headers).text

In [14]:
webpage

'<!doctype html>\n<html lang="en-US" theme="auto" data-color-theme-enabled="true" data-color-scheme="auto" class="desktop neo-green dock-upscale">\n    <head>\n        <meta charset="utf-8" />\n        <meta name="oath:guce:consent-host" content="guce.yahoo.com" />\n        <link rel="preconnect" href="//s.yimg.com" crossorigin="anonymous"><link rel="preconnect" href="//geo.yahoo.com"/><link rel="preconnect" href="//query1.finance.yahoo.com"/><link rel="preconnect" href="//consent.cmp.oath.com"/><link rel="preload" href="/__rapidworker-1.2.js" as="worker"/><link rel="preconnect" href="https://s.yimg.com/uc/finance/webcore/js/_staticFinProtobuf.adb9bf9ae7922cf2dccf.js"/><link rel="preconnect" href="https://cdn.jsdelivr.net/npm/protobufjs@7.1.2/dist/minimal/protobuf.min.js"/><script>window.finNeoPageStart = Date.now();</script><script>\n    (function(){if(!window.YAHOO){window.YAHOO={}};window.YAHOO.context={"consent":{"allowContentPersonalization":true,"allowCrossDeviceMapping":true,"allowFirstPartyAds":true,"allowSellPersonalInfo":true,"canEmbedThirdPartyContent":true,"canSell":true,"consentedVendors":["acast","brightcove","dailymotion","facebook","flourish","giphy","instagram","nbcuniversal","playbuzz","scribblelive","soundcloud","tiktok","vimeo","twitter","youtube","masque"]},"authed":"0","ynet":"0","ssl":"1","spdy":"0","ytee":"0","mode":"normal","tpConsent":true,"site":"finance","adblock":"0","bucket":"","colo":"sg3","device":"desktop","bot":"0","browser":"chrome","app":"unknown","ecma":"modern","environment":"prod","gdpr":false,"lang":"en-US","dir":"ltr","intl":"us","network":"broadband","os":"windows nt","partner":"none","region":"US","time":1772712423923,"tz":"Asia/Kolkata","usercountry":"IN","rmp":"0","webview":"0","feature":["awsCds","disableInterstitialUpsells","disableServiceRewrite","disableBack2Classic","disableYPFTaxArticleDisclosure","enable1PVideoTranscript","enableAdRefresh20s","enableAnalystRatings","enableAPIRedisCaching","enableArticleCSN","enableArticleBodyAdsVariant2","enableArticleBodyInjectionSlot","enableArticleRecommendedVideoInsertion","enableArticleRecommendedVideoInsertionTier34","enableBtmStickyTradeNowCheck","enableCccBoost","enableCGAuthorFeed","enableCGPersonalFinancePagination","enableCGEVPlayer","enableChartbeat","enableChatSupport","enableQSPCommunityService","enableCorporateActions","enablePersonalFinanceOptimizedStream","enablePremiumAdsCSNStyleHandling","enableCompare","enableContentOfferVertical","enableCompareConvertCurrency","enableConsentAndGTM","enableFeatureEngagementSystem","enableCrumbRefresh","enableCSN","enableCurrencyConverter","enableDarkMode","enableDidomi","enableDockAddToFollowing","enableDockPortfolioControl","enableDockTopAd","enableExperimentalDockModules","enableFollow","enableEarningsTranscript","enableEarningsTranscriptAI","enableEntityDiscover","enableEntityDiscoverInStream","enableHistoricalStockPicks","enableHomeNewsStreamNewsletter","enableLazyMidCenter2NAds","enableLazyQSP","enableLocalSpotIM","enableMarketsLeafHeatMap","enableMultiQuote","enableMyMoneyOptIn","enableMyMoneyIntroVideo","enableNeoBasicPFs","enableNeoGreen","enableNeoHouseCalcPage","enableNeoInvestmentIdea","enableNeoMortgageCalcPage","enableNeoQSPReportsLeaf","enableNeoResearchReport","enableNewHomeLayout","enableNimbusSubNav","enableEnhancedScreeners","enableOptimizedStreamDesign","enableOvernight","enablePersonalFinanceNewsletterIntegration","enablePersonalFinanceZillowIntegration","enablePfPremium","enablePfStreaming","enablePinholeScreenshotOGForQuote","enablePlus","enablePolarisSeamlessScrollArticleRecommendations","enablePortalStockStory","enablePrivateCompany","enablePrivateCompanySurvey","enableQSP1PNews","enableQSPAiAnalystSheet","enableQSPAiAnalystSheetChatLatexSupport","enableQSPAiAnalystSheetChatWithZipLambda","enableQSPAiAnalystSheetOnboardingTooltip","enableQSPAiAnalystSheetPriceMovement","enableQSPAnalysisGAAPToggle","enableQSPChartEarnings","enableQSPChartNewShading","enableQSPChartRangeTooltips","enableQSPCryptoLogo","enableQSPDynamicLayout2","enableQSPEarningsVsRev","enableQSPExpandedEarnings","enableQSPChartsFiscalYear","enableQSPHistoryPlusDownload","enableQSPLiveEarnings","enableQSPLiveEarningsFeatureCue","enableQSPHoldingsCard","enableQSPNavIcon","enableQSPQuoteHeaderV2","enableQSPHeaderRedesign","enableQSPPriceInsightsAnomaly","enableQSPAINewsHeadlines","enableQSPStockPicks","enableQSPStockPicksMF","enableQuoteLookup","enableQuoteCoinbaseTradeNow","enableRecentQuotes","enableResearchHub","enableScreenerCustomColumns","enableScreenerHeatMap","enableScreenersCollapseDock","enableScreenersCustomiseResults","enableScreenersSpEarnings","enableScreenersDownload","enableScreenersIndex","enableScreenersExchange","enableSECFiling","enableSkipNav","enableSkipToDock","enableSkipToNav","enableSmartAssetMsgA","enableSpotlightInjectionSlot","enableStockPicksTableSort","enableStockPicksTableFiltering","enableStockStoryPfPage","enableStreamInjectionSlot","enableTickerAIInsights","enableTradeNow","enableUpgradeBadgeDesign","enableUnifiedContentStream","enableVideoInHero","enableDockQuoteEventsModule","enablePfDetailDockCollapse","enablePfPrivateCompany","enableHoneyLinks","partnerAARP","enableFollowedLatestNews","enableCGFollowedLatestNews","enableStockPicks","enableStockPicksCardHome","enableStockPicksProduction","enableDockModuleDescriptions","enableSimpleHeaderCheckout","enableDockFooterSettings","enableDigDeeperArticles","enableDigDeeperArticlesWebview","enableDigDeeperPFArticles","enableDigDeeperPFArticlesWebview","enableDigDeeperProviderFiltering","enableMostPopularCCards","enableCreditCardCompare","enableCreditCardCompositeId","enableGoogleAnalytics","disableMarketPsychForStockMarketNews","enableTransparentChart","disableSustainability","enablePolarisPfReadMoreStream","enableTransUnionLandingPage","conditonallyDisableTopicFollow","enableCommunityTxnToken","disablePredictionMarketsBEFeatured","enablePredictionMarkets","enablePredictionMarketsBE","enablePredictionMarketsNewLabel","disablePredictionMarketsPolling","enableNewVideoLivePlacement","disableLiveBugOnVideos","enableNewsHubModularContent","enableTopicModularContent","enableCreditCardComparePFArticle","enableMortgageCalculatorDirectLink","enableSlimNavBar","enableCompareFeatures","enableGenericHeatMap","enableQSPIndustryHeatmap"],"isDebug":false,"isForScreenshot":false,"isWebview":false,"theme":"auto","pnrID":"","isError":false,"gucJurisdiction":"","areAdsEnabled":true,"ccpa":{"warning":"","footerSequence":["terms_and_privacy","dashboard"],"links":{"dashboard":{"url":"https://guce.yahoo.com/privacy-dashboard?locale=en-US","label":"Privacy Dashboard","id":"privacy-link-dashboard"},"terms_and_privacy":{"multiurl":true,"label":"${terms_link}Terms${end_link} and ${privacy_link}Privacy Policy${end_link}","urls":{"terms_link":"https://guce.yahoo.com/terms?locale=en-US","privacy_link":"https://guce.yahoo.com/privacy-policy?locale=en-US"},"ids":{"terms_link":"privacy-link-terms-link","privacy_link":"privacy-link-privacy-link"}}}},"yrid":"2d5oflhkqisf7","user":{"age":0,"firstName":null,"gender":"","year":0},"clientVersion":"0.1.12047.1772673475"};})();</script><script>function onRapidAssetLoad(){if(typeof onRapidLoad === "function"){onRapidLoad()}}</script><script>function initFinSearch(){window.FinSearch?.init({"uiConfig":{"isSearchRedesign":true,"isNeoGreen":true,"showStockStory":false},"searchConfig":{"recommendCount":5,"enableCccBoost":true,"enablePrivateCompany":true,"enableCb":false}});}</script><script>!function(){var e={1040:function(e){"use strict";function t(e){return(t="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e})(e)}e.exports=function(){for(var e,n,a=[],s=window,r=s;r;){try{if(r.frames.__tcfapiLocator){e=r;break}}catch(e){}if(r===s.top)break;r=r.parent}e||(function e(){var t=s.document,n=!!s.frames.__tcfapiLocator;if(!n)if(t.body){var a=t.createElement("iframe");a.style.cssText="display:none",a.name="__tcfapiLocator",t.body.appendChild(a)}else setTimeout(e,5);return!n}(),s.__tcfapi=function(){for(var e=arguments.length,t=new Array(e),s=0;s<e;s++)t[s]=arguments[s];if(!t.length)return a;"setGdprApplies"===t[0]?t.length>3&&2===parseInt(t[1],10)&&"boolean"==typeof t[3]&&(n=t[3],"function"==typeof t[2]&&t[2]("set",!0)):"ping"===t[0]?"function"==typeof t[2]&&t[2]({gdprApplies:n,cmpLoaded:!1,cmpStatus:"stub"}):a.push(t)},s.addEventListener("message",(function(e){var n="string"==typeof e.data,a={};if(n)try{a=JSON.parse(e.data)}catch(e){}else a=e.data;var s="object"===t(a)&&null!==a?a.__tcfapiCall:null;s&&window.__tcfapi(s.command,s.version,(function(t,a){var r={__tcfapiReturn:{returnValue:t,success:a,callId:s.callId}};e&&e.source&&e.source.postMessage&&e.source.postMessage(n?JSON.stringify(r):r,"*")}),s.parameter)}),!1))}},5385:function(){"use strict";window.__gpp_addFrame=function(e){if(!window.frames[e])if(document.body){var t=document.createElement("iframe");t.style.cssText="display:none",t.name=e,document.body.appendChild(t)}else window.setTimeout(window.__gpp_addFrame,10,e)},window.__gpp_stub=function(){var e=arguments;if(__gpp.queue=__gpp.queue||[],__gpp.events=__gpp.events||[],!e.length||1==e.length&&"queue"==e[0])return __gpp.queue;if(1==e.length&&"events"==e[0])return __gpp.events;var t=e[0],n=e.length>1?e[1]:null,a=e.length>2?e[2]:null;if("ping"===t)n({gppVersion:"1.1",cmpStatus:"stub",cmpDisplayStatus:"hidden",signalStatus:"not ready",supportedAPIs:["2:tcfeuv2","5:tcfcav1","6:uspv1","7:usnatv1","8:uscav1","9:usvav1","10:uscov1","11:usutv1","12:usctv1"],cmpId:0,sectionList:[],applicableSections:[],gppString:"",parsedSections:{}},!0);else if("addEventListener"===t){"lastId"in __gpp||(__gpp.lastId=0),__gpp.lastId++;var s=__gpp.lastId;__gpp.events.push({id:s,callback:n,parameter:a}),n({eventName:"listenerRegistered",listenerId:s,data:!0,pingData:{gppVersion:"1.1",cmpStatus:"stub",cmpDisplayStatus:"hidden",signalStatus:"not ready",supportedAPIs:["2:tcfeuv2","5:tcfcav1","6:uspv1","7:usnatv1","8:uscav1","9:usvav1","10:uscov1","11:usutv1","12:usctv1"],cmpId:0,sectionList:[],applicableSections:[],gppString:"",parsedSections:{}}},!0)}else if("removeEventListener"===t){for(var r=!1,o=0;o<__gpp.events.length;o++)if(__gpp.events[o].id==a){__gpp.events.splice(o,1),r=!0;break}n({eventName:"listenerRemoved",listenerId:a,data:r,pingData:{gppVersion:"1.1",cmpStatus:"stub",cmpDisplayStatus:"hidden",signalStatus:"not ready",supportedAPIs:["2:tcfeuv2","5:tcfcav1","6:uspv1","7:usnatv1","8:uscav1","9:usvav1","10:uscov1","11:usutv1","12:usctv1"],cmpId:0,sectionList:[],applicableSections:[],gppString:"",parsedSections:{}}},!0)}else"hasSection"===t?n(!1,!0):"getSection"===t||"getField"===t?n(null,!0):__gpp.queue.push([].slice.apply(e))},window.__gpp_msghandler=function(e){var t="string"==typeof e.data;try{var n=t?JSON.parse(e.data):e.data}catch(e){n=null}if("object"==typeof n&&null!==n&&"__gppCall"in n){var a=n.__gppCall;window.__gpp(a.command,(function(n,s){var r={__gppReturn:{returnValue:n,success:s,callId:a.callId}};e.source.postMessage(t?JSON.stringify(r):r,"*")}),"parameter"in a?a.parameter:null,"version"in a?a.version:"1.1")}},"__gpp"in window&&"function"==typeof window.__gpp||(window.__gpp=window.__gpp_stub,window.addEventListener("message",window.__gpp_msghandler,!1),window.__gpp_addFrame("__gppLocator"))},1007:function(e,t,n){"use strict";n.r(t);var a=n(1040);n.n(a)()()},9476:function(){!function(){for(var e,t="__uspapiLocator",n=[],a=window;a;){try{if(a.frames[t]){e=a;break}}catch(e){}if(a===window.top)break;a=a.parent}e||(function e(){var n=window.document;if(!window.frames[t])if(n.body){var a=n.createElement("iframe");a.style.cssText="display:none",a.name=t,n.body.appendChild(a)}else setTimeout(e,5)}(),window.__uspapi=function(){for(var e=arguments.length,t=new Array(e),a=0;a<e;a++)t[a]=arguments[a];if(!t.length)return n;n.push(t)},window.addEventListener("message",(function(e){var t="string"==typeof e.data,n={};try{n=t?JSON.parse(e.data):e.data}catch(e){}var a=n.__uspapiCall;a&&window.__uspapi(a.command,a.version,(function(n,s){var r={__uspapiReturn:{returnValue:n,success:s,callId:a.callId}};t&&(r=JSON.stringify(r)),e&&e.source&&e.source.postMessage(r,"*")}),a.parameter)}),!1))}()}},t={};function n(a){var s=t[a];if(void 0!==s)return s.exports;var r=t[a]={exports:{}};return e[a](r,r.exports,n),r.exports}n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,{a:t}),t},n.d=function(e,t){for(var a in t)n.o(t,a)&&!n.o(e,a)&&Object.defineProperty(e,a,{enumerable:!0,get:t[a]})},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},function(){"use strict";n(9476);!window.document.documentMode&&(n(1007),n(5385))}()}();</script><script>(function(){window.YAHOO=window.YAHOO||{};window.YAHOO.comscore=window.YAHOO.comscore||{"c1":2,"c2":"7241469","cs_fpit":"c","cs_fpdt":"01","c14":-1,"cs_fpdm":"*null"};})();</script><script>\nwindow._nimbusEvLoad = window._nimbusEvLoad || { _player: false };\n            function _nimbusSendEVLoadEvent() {\n                if (_nimbusEvLoad._player){\n                    window.finNeoEVReady = Date.now();\n                    window.dispatchEvent(new CustomEvent(\'NIMBUS_EV_READY\',{detail: {}}));\n                }\n            }\n            function onNimbusEVPlayerReady(){_nimbusEvLoad._player = true;_nimbusSendEVLoadEvent();}\n</script><script type="module">if(!window.finWebCore){window.finWebCore=function r(e){const{isModern:t=!0,isDev:i=!1,lang:a=s,devAssets:o,prodAssets:r,crumb:n="",features:c=[],throttle:d={},strings:f}=e;let m={};const u=a.substring(a.lastIndexOf("-")+1);return{crumb:n,lang:a,region:u,features:c,throttle:d,store:{},intl:u.toLowerCase(),strings:f,assets:i?o:r,addScriptTag(e,s,t){if(!e)return;const i=document.createElement("script");i.setAttribute("src",e),i.setAttribute("type","text/javascript"),"function"==typeof t&&(i.onload=()=>{t(!0)},i.onerror=()=>{t(!1)});for(const e in s)e&&Object.prototype.hasOwnProperty.call(s,e)&&void 0!==s[e]&&i.setAttribute(e,s[e]);document.body.appendChild(i)},addAsset(e,s={}){const{async:a=!0,defer:n,useModule:c=!1,callback:d}=s;if(m[e])return void("function"==typeof d&&d(!0));let f;if(f=i?o:r,!f||0===f.length)return;m[e]=!0;let u=f[0]&&f[0][e]&&f[0][e].mjs;c?(this.addScriptTag(u,{async:a,defer:n,type:"module"},d),f.length>1&&!i&&(u=f[1]&&f[1][e]&&f[1][e].js,this.addScriptTag(u,{async:a,defer:n,nomodule:!0},d))):(f.length>1&&!t&&(u=f[1]&&f[1][e]&&f[1][e].js),this.addScriptTag(u,{async:a,defer:n},d))},reset(){m={}}}}({isModern:true,isDev:false,lang:\'en-US\',features:[],throttle:{"quote":200},devAssets:{},prodAssets:[{"_staticFinProtobuf":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/_staticFinProtobuf.adb9bf9ae7922cf2dccf.mjs"},"chart":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/chart.4af97cf348f0fb4285bc.mjs"},"cryptoTrade":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/cryptoTrade.90069b540b1d7f607ff2.mjs"},"finBankrateMortgageOffers":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/finBankrateMortgageOffers.f1b4562c7291c86e835a.mjs"},"finBarChart":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/finBarChart.0f62599d2a91ea115d72.mjs"},"finGaugeChart":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/finGaugeChart.b4564035a716b8335990.mjs"},"finHorizontalBarChart":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/finHorizontalBarChart.fad7988e98a8ce40db10.mjs"},"finIcon":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/finIcon.303dcbfc0a8c9e028f3e.mjs"},"finPlaidLink":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/finPlaidLink.90255bca09303ecdc32e.mjs"},"finVizChart":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/finVizChart.82d364064910686d6aef.mjs"},"finYodlee":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/finYodlee.65cc6a72e9914ef8ea8f.mjs"},"importantDates":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/importantDates.1a882e5ecd6fb730872c.mjs"},"marketSummary":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/marketSummary.18341e4515c27be02c47.mjs"},"marketTime":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/marketTime.1141e6af2858c5e11c04.mjs"},"navigation":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/navigation.f66fe770e554cb0bb7d7.mjs"},"portfolio":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/portfolio.1a460d914f65dc3f7103.mjs"},"quoteSummary":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/quoteSummary.1be372cc8a25ac597f40.mjs"},"sparkLine":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/sparkLine.be4a748c75a1f617d549.mjs"},"sprig":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/sprig.a2b66c2c55287e9c86f4.mjs"},"streamer":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/streamer.14808ea27a17ff2419d2.mjs"},"ticker":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/ticker.d14c9dbdfde76cc83fcc.mjs"},"xrayStocks":{"mjs":"https://s.yimg.com/uc/finance/webcore/js/xrayStocks.b51ba82541bad67b52d5.mjs"},"":{"mjs":["https://s.yimg.com/uc/finance/webcore/js/382.055aa829c9cf91548d6e.mjs","https://s.yimg.com/uc/finance/webcore/js/portfolio.worker.ce3eaa8f91eba0e3c283.worker.mjs","https://s.yimg.com/uc/finance/webcore/js/streamer.worker.08e3d2e95663b47bd092.worker.mjs"]}},{"_staticFinProtobuf":{"js":"https://s.yimg.com/uc/finance/webcore/js/_staticFinProtobuf.adb9bf9ae7922cf2dccf.js"},"chart":{"js":"https://s.yimg.com/uc/finance/webcore/js/chart.cc24a2b90efb8c04f483.js"},"cryptoTrade":{"js":"https://s.yimg.com/uc/finance/webcore/js/cryptoTrade.417fa9618f3a8fea6d8d.js"},"finBankrateMortgageOffers":{"js":"https://s.yimg.com/uc/finance/webcore/js/finBankrateMortgageOffers.338f16f39db2d272f169.js"},"finBarChart":{"js":"https://s.yimg.com/uc/finance/webcore/js/finBarChart.b7483c80a2ebe3ea29c5.js"},"finGaugeChart":{"js":"https://s.yimg.com/uc/finance/webcore/js/finGaugeChart.7ea1c7a3ddefe4041d30.js"},"finHorizontalBarChart":{"js":"https://s.yimg.com/uc/finance/webcore/js/finHorizontalBarChart.20bae46a123bdcd5dbca.js"},"finIcon":{"js":"https://s.yimg.com/uc/finance/webcore/js/finIcon.c0a0f64c3dae0298f8c9.js"},"finPlaidLink":{"js":"https://s.yimg.com/uc/finance/webcore/js/finPlaidLink.93957704437db323444a.js"},"finVizChart":{"js":"https://s.yimg.com/uc/finance/webcore/js/finVizChart.d6f669b8d4400d1830aa.js"},"finYodlee":{"js":"https://s.yimg.com/uc/finance/webcore/js/finYodlee.f7fec31ba4a422ad9bfe.js"},"importantDates":{"js":"https://s.yimg.com/uc/finance/webcore/js/importantDates.63231744b3f3c45d8e25.js"},"marketSummary":{"js":"https://s.yimg.com/uc/finance/webcore/js/marketSummary.ed61671e0327b67d6b94.js"},"marketTime":{"js":"https://s.yimg.com/uc/finance/webcore/js/marketTime.7897a5f78c81f4ee1a8e.js"},"navigation":{"js":"https://s.yimg.com/uc/finance/webcore/js/navigation.dece7d622e27f04c282c.js"},"portfolio":{"js":"https://s.yimg.com/uc/finance/webcore/js/portfolio.a3456cbda2b01102e175.js"},"quoteSummary":{"js":"https://s.yimg.com/uc/finance/webcore/js/quoteSummary.68a66e32992e50724401.js"},"sparkLine":{"js":"https://s.yimg.com/uc/finance/webcore/js/sparkLine.0413e9efc189c72a7dbd.js"},"sprig":{"js":"https://s.yimg.com/uc/finance/webcore/js/sprig.bdc1efef1c947a4a4e98.js"},"streamer":{"js":"https://s.yimg.com/uc/finance/webcore/js/streamer.805122418fd188cbc286.js"},"ticker":{"js":"https://s.yimg.com/uc/finance/webcore/js/ticker.353159827c97cbbf1e47.js"},"xrayStocks":{"js":"https://s.yimg.com/uc/finance/webcore/js/xrayStocks.cfb746bcc57448c2f3f6.js"},"":{"js":["https://s.yimg.com/uc/finance/webcore/js/382.055aa829c9cf91548d6e.js","https://s.yimg.com/uc/finance/webcore/js/portfolio.worker.7882b59fd43d10295094.worker.js","https://s.yimg.com/uc/finance/webcore/js/streamer.worker.04912daa7ab1221ed99d.worker.js"]}}],strings:{"AUTHENTICATING":"Authentica

In [16]:
soup=BeautifulSoup(webpage,'lxml')

In [17]:
print(soup.prettify())

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [22]:
table=soup.find('table')

In [27]:
tbody=table.find('tbody')

In [29]:
len(tbody.find_all('tr'))

100

In [30]:
tbody.find_all('tr')[0]

<tr class="row yf-1tpeyy7" data-testid="data-table-v2-row" data-testid-row="0"> <td class="[&amp;_.symbol]:tw-text-md yf-1tpeyy7 lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-1pdfbgz"><a aria-label="NVIDIA Corporation" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-1pdfbgz" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"stocks-datatable","yLinkText":"NVDA"}' data-ylk="elm:qte;elmt:link;itc:0;sec:stocks-datatable;slk:NVDA" href="/quote/NVDA/" title="NVIDIA Corporation"> <div class="name yf-1pdfbgz"> <span class="symbol yf-1pdfbgz">NVDA </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1tpeyy7" data-testid-cell="companyshortname.raw" style="--_depth: false;"> <div class="leftAlignHeader companyName yf-362rys enableMaxWidth" title="NVIDIA Corporation">NVIDIA Corporation </div> </td> <td class="yf-1tpeyy7" data-testid-cell="sparkline" style="--_depth: false;"> <div class="yf-1rh4oll expandWidth enableMaxWidth"><a aria-label="Advanced Chart" class="none-link fin-size-small yf-119g04z" data-yga='{"yLinkElement":"chart","yLinkElementType":"link","yModuleName":"stocks-datatable","yLinkText":"NVDA"}' data-ylk="elm:chart;elmt:link;itc:0;sec:stocks-datatable;slk:NVDA" href="/chart/NVDA"><figure class="yf-v6nywu contain-paint" data-testid="sparkline"><canvas aria-label="NVDA chart" class="yf-v6nywu"></canvas></figure> </a> </div> </td> <td class="yf-1tpeyy7" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-qgwoh6 base" data-testid="change">183.04 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="2.990097">+2.99</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="1.6607037">(+1.66%)</fin-streamer></div></div> </td> <td class="yf-1tpeyy7" data-testid-cell="intradaypricechange" style="--_depth: false;"> <span class="txt-positive yf-qgwoh6 base" data-testid="colorChange">+2.99 </span> </td> <td class="yf-1tpeyy7" data-testid-cell="percentchange" style="--_depth: false;"> <span class="txt-positive yf-qgwoh6 base" data-testid="colorChange">+1.66% </span> </td> <td class="yf-1tpeyy7" data-testid-cell="dayvolume" style="--_depth: false;"> <span class="yf-qgwoh6 base" data-testid="change">155.809M </span> </td> <td class="yf-1tpeyy7" data-testid-cell="avgdailyvol3m" style="--_depth: false;">      176.008M </td> <td class="yf-1tpeyy7" data-testid-cell="intradaymarketcap" style="--_depth: false;"> <span class="yf-qgwoh6 base" data-testid="change">4.449T </span> </td> <td class="yf-1tpeyy7" data-testid-cell="peratio.lasttwelvemonths" style="--_depth: false;">      37.24 </td> <td class="yf-1tpeyy7" data-testid-cell="fiftytwowkpercentchange" style="--_depth: false;"> <span class="txt-positive yf-qgwoh6 base" data-testid="colorChange">+65.54% </span> </td> <td class="yf-1tpeyy7" data-testid-cell="fiftyTwoWeekRange" style="--_depth: false;"> <div aria-label="Graph showing stock performance over fifty two week range" class="container yf-wummfw" role="img"><div class="line yf-wummfw" style="top: 11px;height: 2px;"><div class="candle yf-wummfw" style="top: 0;height: 2px;left: 97.00px;width: 9px;"></div> <svg class="yf-wummfw" height="10" style="top: -12px; left: 103px;" viewbox="0 0 80 110" width="8" xmlns="http://www.w3.org/2000/svg"><path d="M 0 40 A 40 40 0 0 1 80 40 L 40 110 Z"></path></svg></div> <div class="labels yf-wummfw"><span>86.62</span> <span>212.19</span></div> </div> </td></tr>

In [50]:
for i in (tbody.find_all('tr')[0].find_all('td')):
    print(i.text,"\n")

   NVDA

 NVIDIA Corporation



  183.04  +2.99 (+1.66%)

 +2.99

 +1.66%

 155.809M

      176.008M

 4.449T

      37.24

 +65.54%

   86.62 212.19

In [48]:
tbody.find_all('tr')[0].find_all('td')[3]

<td class="yf-1tpeyy7" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-qgwoh6 base" data-testid="change">183.04 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="2.990097">+2.99</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="1.6607037">(+1.66%)</fin-streamer></div></div> </td>

In [51]:
tr_list=tbody.find_all('tr')[0].find_all('td')

In [73]:
l=[tr_list[0].text.strip(),tr_list[1].text.strip(),float(tr_list[3].text.strip().split()[0]),tr_list[4].text.strip(),tr_list[5].text.strip(),tr_list[6].text.strip(),tr_list[7].text.strip(),tr_list[8].text.strip(),tr_list[9].text.strip(),tr_list[10].text.strip()]
l.extend(tr_list[11].text.strip().split())
l[-1]=float(l[-1])
l[-2]=float(l[-2])

In [61]:
l

['NVDA',
 'NVIDIA Corporation',
 '  183.04  +2.99 (+1.66%) ',
 '+2.99',
 '+1.66%',
 '155.809M',
 '176.008M',
 '4.449T',
 '37.24',
 '+65.54%',
 '   86.62 212.19  ']

In [74]:
l

['NVDA',
 'NVIDIA Corporation',
 183.04,
 '+2.99',
 '+1.66%',
 '155.809M',
 '176.008M',
 '4.449T',
 '37.24',
 '+65.54%',
 86.62,
 212.19]

In [75]:
twoD=[]
for i in range(0,100):
    tr_list=tbody.find_all('tr')[i].find_all('td')
    l=[tr_list[0].text.strip(),tr_list[1].text.strip(),float(tr_list[3].text.strip().split()[0]),tr_list[4].text.strip(),tr_list[5].text.strip(),tr_list[6].text.strip(),tr_list[7].text.strip(),tr_list[8].text.strip(),tr_list[9].text.strip(),tr_list[10].text.strip()]
    l.extend(tr_list[11].text.strip().split())
    l[-1]=float(l[-1])
    l[-2]=float(l[-2])
    twoD.append(l)

In [76]:
twoD

[['NVDA',
  'NVIDIA Corporation',
  183.04,
  '+2.99',
  '+1.66%',
  '155.809M',
  '176.008M',
  '4.449T',
  '37.24',
  '+65.54%',
  86.62,
  212.19],
 ['PLUG',
  'Plug Power Inc.',
  2.48,
  '+0.25',
  '+11.21%',
  '124.832M',
  '100.523M',
  '3.451B',
  '--',
  '+50.30%',
  0.69,
  4.58],
 ['ONDS',
  'Ondas Inc.',
  10.51,
  '+0.49',
  '+4.89%',
  '96.532M',
  '92.64M',
  '4.73B',
  '--',
  '+1,205.59%',
  0.57,
  15.28],
 ['INTC',
  'Intel Corporation',
  45.58,
  '+2.48',
  '+5.75%',
  '84.551M',
  '101.517M',
  '227.68B',
  '--',
  '+119.66%',
  17.67,
  54.6],
 ['NOK',
  'Nokia Oyj',
  8.15,
  '+0.08',
  '+0.99%',
  '68.544M',
  '35.129M',
  '45.498B',
  '62.09',
  '+57.95%',
  4.0,
  8.37],
 ['F',
  'Ford Motor Company',
  12.81,
  '+0.11',
  '+0.87%',
  '67.643M',
  '62.864M',
  '51.105B',
  '--',
  '+33.30%',
  8.44,
  14.8],
 ['AAL',
  'American Airlines Group Inc.',
  12.46,
  '0.00',
  '0.00%',
  '64.343M',
  '57.372M',
  '8.227B',
  '74.44',
  '-5.96%',
  8.5,
  16.5],
 ['TSLA',
  'Tesla, Inc.',
  406.2,
  '+13.77',
  '+3.51%',
  '62.757M',
  '65.723M',
  '1.524T',
  '373.44',
  '+54.09%',
  214.25,
  498.83],
 ['MARA',
  'MARA Holdings, Inc.',
  9.29,
  '+0.63',
  '+7.27%',
  '58.516M',
  '44.741M',
  '3.513B',
  '--',
  '-38.44%',
  6.66,
  23.45],
 ['SOFI',
  'SoFi Technologies, Inc.',
  18.71,
  '+0.10',
  '+0.54%',
  '57.352M',
  '56.027M',
  '23.86B',
  '47.69',
  '+49.48%',
  8.6,
  32.73],
 ['BMNR',
  'Bitmine Immersion Technologies, Inc.',
  21.12,
  '+1.55',
  '+7.92%',
  '57.155M',
  '44.015M',
  '9.607B',
  '--',
  '+152.52%',
  3.92,
  161.0],
 ['NU',
  'Nu Holdings Ltd.',
  15.0,
  '+0.24',
  '+1.63%',
  '56.217M',
  '49.528M',
  '72.684B',
  '25.98',
  '+40.85%',
  9.01,
  18.98],
 ['PLTR',
  'Palantir Technologies Inc.',
  153.18,
  '+5.96',
  '+4.05%',
  '55.129M',
  '47.485M',
  '366.357B',
  '230.43',
  '+90.39%',
  66.12,
  207.52],
 ['NIO',
  'NIO Inc.',
  4.84,
  '+0.25',
  '+5.45%',
  '49.69M',
  '42.214M',
  '12.239B',
  '--',
  '+14.15%',
  3.02,
  8.02],
 ['BBD',
  'Banco Bradesco S.A.',
  3.91,
  '+0.10',
  '+2.72%',
  '47.448M',
  '36.907M',
  '41.547B',
  '9.49',
  '+89.81%',
  1.95,
  4.29],
 ['AMZN',
  'Amazon.com, Inc.',
  216.82,
  '+8.09',
  '+3.88%',
  '46.814M',
  '48.036M',
  '2.328T',
  '29.06',
  '+8.03%',
  161.38,
  258.6],
 ['NFLX',
  'Netflix, Inc.',
  98.66,
  '+0.96',
  '+0.98%',
  '46.689M',
  '51.036M',
  '418.505B',
  '38.38',
  '+8.85%',
  75.01,
  134.12],
 ['GRAB',
  'Grab Holdings Limited',
  4.1,
  '+0.02',
  '+0.49%',
  '40.968M',
  '47.102M',
  '16.812B',
  '69.67',
  '-10.87%',
  3.36,
  6.62],
 ['KVUE',
  'Kenvue Inc.',
  18.19,
  '+0.04',
  '+0.22%',
  '37.761M',
  '45.135M',
  '34.865B',
  '24.86',
  '-21.53%',
  14.02,
  25.17],
 ['VALE',
  'Vale S.A.',
  16.06,
  '+0.09',
  '+0.56%',
  '36.26M',
  '36.353M',
  '68.557B',
  '27.29',
  '+64.21%',
  8.06,
  17.72],
 ['VG',
  'Venture Global, Inc.',
  11.16,
  '-0.30',
  '-2.62%',
  '35.955M',
  '13.495M',
  '27.321B',
  '13.23',
  '+22.64%',
  5.72,
  19.5],
 ['HOOD',
  'Robinhood Markets, Inc.',
  82.21,
  '+6.14',
  '+8.07%',
  '35.749M',
  '28.165M',
  '74.014B',
  '38.43',
  '+83.34%',
  29.66,
  153.86],
 ['AMD',
  'Advanced Micro Devices, Inc.',
  202.13,
  '+11.18',
  '+5.85%',
  '35.634M',
  '36.176M',
  '329.555B',
  '76.10',
  '+104.42%',
  76.48,
  267.08],
 ['WBD',
  'Warner Bros. Discovery, Inc.',
  27.95,
  '-0.25',
  '-0.89%',
  '34.895M',
  '36.498M',
  '69.313B',
  '98.28',
  '+161.21%',
  7.52,
  30.0],
 ['PATH',
  'UiPath, Inc.',
  11.07,
  '+0.03',
  '+0.27%',
  '34.399M',
  '29.225M',
  '5.92B',
  '25.45',
  '-5.79%',
  9.38,
  19.84],
 ['RIG',
  'Transocean Ltd.',
  6.37,
  '+0.26',
  '+4.26%',
  '33.951M',
  '44.698M',
  '7.025B',
  '--',
  '+120.58%',
  1.97,
  6.96],
 ['IREN',
  'IREN Limited',
  43.84,
  '+4.99',
  '+12.84%',
  '33.343M',
  '38.093M',
  '14.544B',
  '31.02',
  '+475.33%',
  5.13,
  76.87],
 ['SNAP',
  'Snap Inc.',
  5.37,
  '+0.12',
  '+2.29%',
  '33.326M',
  '47.315M',
  '9.07B',
  '--',
  '-44.06%',
  4.65,
  10.41],
 ['MSTR',
  'Strategy Inc',
  146.53,
  '+13.85',
  '+10.44%',
  '33.097M',
  '22.196M',
  '48.905B',
  '--',
  '-51.85%',
  104.17,
  457.22],
 ['ITUB',
  'Itaú Unibanco Holding S.A.',
  8.61,
  '+0.21',
  '+2.50%',
  '32.559M',
  '23.958M',
  '94.939B',
  '11.45',
  '+72.05%',
  4.91,
  9.6],
 ['MSFT',
  'Microsoft Corporation',
  405.2,
  '+1.27',
  '+0.31%',
  '32.444M',
  '33.343M',
  '3.012T',
  '24.94',
  '+2.09%',
  344.79,
  555.45],
 ['MU',
  'Micron Technology, Inc.',
  400.77,
  '+21.09',
  '+5.55%',
  '32.266M',
  '33.961M',
  '451.07B',
  '39.15',
  '+325.32%',
  61.54,
  455.5],
 ['T',
  'AT&T Inc.',
  28.98,
  '+0.31',
  '+1.08%',
  '32.115M',
  '43.095M',
  '205.452B',
  '9.18',
  '+8.42%',
  22.95,
  29.79],
 ['IBRX',
  'ImmunityBio, Inc.',
  9.0,
  '-1.00',
  '-10.00%',
  '31.615M',
  '35.959M',
  '9.253B',
  '--',
  '+201.00%',
  1.83,
  12.43],
 ['CRGY',
  'Crescent Energy Company',
  11.51,
  '+0.27',
  '+2.40%',
  '31.276M',
  '6.885M',
  '3.78B',
  '22.20',
  '+6.38%',
  6.83,
  12.4],
 ['OWL',
  'Blue Owl Capital Inc.',
  10.34,
  '+0.07',
  '+0.68%',
  '30.319M',
  '23.329M',
  '16.135B',
  '103.44',
  '-46.59%',
  9.73,
  21.88],
 ['NCLH',
  'Norwegian Cruise Line Holdings Ltd.',
  21.11,
  '-0.16',
  '-0.75%',
  '29.709M',
  '20.769M',
  '9.61B',
  '24.24',
  '+5.55%',
  14.21,
  27.18],
 ['RKT',
  'Rocket Companies, Inc.',
  16.63,
  '+0.20',
  '+1.22%',
  '29.338M',
  '28.183M',
  '46.828B',
  '--',
  '+11.99%',
  10.94,
  24.36],
 ['SMCI',
  'Super Micro Computer, Inc.',
  32.65,
  '+1.98',
  '+6.44%',
  '29.036M',
  '29.54M',
  '19.557B',
  '23.24',
  '-17.19%',
  27.6,
  62.36],
 ['CMCSA',
  'Comcast Corporation',
  32.09,
  '+1.08',
  '+3.48%',
  '28.493M',
  '35.893M',
  '116.933B',
  '5.72',
  '-8.77%',
  24.13,
  35.6],
 ['EOSE',
  'Eos Energy Enterprises, Inc.',
  6.75,
  '+0.69',
  '+11.39%',
  '28.081M',
  '22.305M',
  '2.188B',
  '--',
  '+49.01%',
  3.07,
  19.86],
 ['HBAN',
  'Huntington Bancshares Incorporated',
  16.83,
  '+0.08',
  '+0.48%',
  '27.678M',
  '32.144M',
  '34.161B',
  '12.21',
  '+11.24%',
  11.92,
  19.46],
 ['BAC',
  'Bank of America Corporation',
  50.3,
  '+0.33',
  '+0.66%',
  '27.47M',
  '40.272M',
  '502.409B',
  '13.07',
  '+21.32%',
  33.07,
  57.55],
 ['OPEN',
  'Opendoor Technologies Inc.',
  4.88,
  '-0.09',
  '-1.81%',
  '27.325M',
  '56.329M',
  '4.677B',
  '--',
  '+313.56%',
  0.51,
  10.87],
 ['AAPL',
  'Apple Inc.',
  262.52,
  '-1.23',
  '-0.47%',
  '27.103M',
  '48.111M',
  '3.858T',
  '33.57',
  '+11.55%',
  169.21,
  288.62],
 ['COIN',
  'Coinbase Global, Inc.',
  208.93,
  '+26.57',
  '+14.57%',
  '27.1M',
  '11.224M',
  '56.34B',
  '41.65',
  '-2.45%',
  139.36,
  444.65],
 ['PFE',
  'Pfizer Inc.',
  26.62,
  '+0.04',
  '+0.15%',
  '25.764M',
  '47.512M',
  '151.354B',
  '20.04',
  '+1.45%',
  20.92,
  27.94],
 ['NVO',
  'Novo Nordisk A/S',
  38.5,
  '+1.84',
  '+5.02%',
  '25.281M',
  '24.005M',
  '171.127B',
  '10.31',
  '-56.27%',
  35.85,
  89.03],
 ['ACHR',
  'Archer Aviation Inc.',
  6.76,
  '+0.04',
  '+0.60%',
  '25.078M',
  '36.889M',
  '4.963B',
  '--',
  '-10.58%',
  5.48,
  14.62],
 ['CRWV',
  'CoreWeave, Inc.',
  79.5,
  '+5.72',
  '+7.75%',
  '24.992M',
  '28.241M',
  '41.44B',
  '--',
  '+98.75%',
  33.52,
  187.0],
 ['BULL',
  'Webull Corporation',
  6.07,
  '+0.11',
  '+1.85%',
  '24.24M',
  '11.962M',
  '3.046B',
  '--',
  '-47.90%',
  5.47,
  79.56],
 ['RIVN',
  'Rivian Automotive, Inc.',
  14.92,
  '-0.18',
  '-1.19%',
  '23.742M',
  '35.826M',
  '18.516B',
  '--',
  '+35.27%',
  10.36,
  22.69],
 ['PINS',
  'Pinterest, Inc.',
  19.38,
  '+0.28',
  '+1.47%',
  '23.643M',
  '18.875M',
  '13.092B',
  '28.66',
  '-44.65%',
  13.84,
  39.93],
 ['WULF',
  'TeraWulf Inc.',
  15.37,
  '+0.63',
  '+4.27%',
  '23.6M',
  '30.412M',
  '6.435B',
  '--',
  '+357.44%',
  2.06,
  18.51],
 ['GTLB',
  'GitLab Inc.',
  25.05,
  '-1.65',
  '-6.18%',
  '23.332M',
  '5.398M',
  '4.218B',
  '--',
  '-57.00%',
  23.1,
  61.16],
 ['DNN',
  'Denison Mines Corp.',
  4.12,
  '+0.12',
  '+3.00%',
  '23.063M',
  '45.865M',
  '3.697B',
  '--',
  '+188.11%',
  1.08,
  4.43],
 ['SAN',
  'Banco Santander, S.A.',
  11.57,
  '+0.54',
  '+4.90%',
  '23.002M',
  '10.124M',
  '171.524B',
  '12.88',
  '+74.51%',
  5.54,
  13.24],
 ['AVGO',
  'Broadcom Inc.',
  317.37,
  '+3.53',
  '+1.12%',
  '22.379M',
  '31.098M',
  '1.505T',
  '66.84',
  '+74.89%',
  138.1,
  414.61],
 ['CRCL',
  'Circle Internet Group',
  105.27,
  '+5.64',
  '+5.66%',
  '22.135M',
  '13.095M',
  '26.785B',
  '--',
  '+26.48%',
  49.9,
  298.99],
 ['GOOGL',
  'Alphabet Inc.',
  303.16,
  '-0.42',
  '-0.14%',
  '21.999M',
  '34.401M',
  '3.667T',
  '28.38',
  '+75.88%',
  140.53,
  349.0],
 ['RGTI',
  'Rigetti Computing, Inc.',
  17.77,
  '+0.81',
  '+4.78%',
  '21.525M',
  '31.986M',
  '5.865B',
  '--',
  '+108.70%',
  6.86,
  58.15],
 ['CLSK',
  'CleanSpark, Inc.',
  10.66,
  '+0.77',
  '+7.79%',
  '21.476M',
  '27.452M',
  '2.726B',
  '--',
  '+30.80%',
  6.45,
  23.61],
 ['MRNA',
  'Moderna, Inc.',
  57.8,
  '+7.97',
  '+15.99%',
  '21.17M',
  '11.938M',
  '22.827B',
  '--',
  '+68.51%',
  22.28,
  59.55],
 ['CIFR',
  'Cipher Digital Inc.',
  16.04,
  '+1.33',
  '+9.04%',
  '20.973M',
  '30.304M',
  '6.498B',
  '--',
  '+323.22%',
  1.86,
  25.52],
 ['CPNG',
  'Coupang, Inc.',
  19.1,
  '-0.11',
  '-0.57%',
  '20.77M',
  '24.228M',
  '34.889B',
  '180.27',
  '-17.57%',
  16.74,
  34.08],
 ['AGNC',
  'AGNC Investment Corp.',
  10.97,
  '-0.03',
  '-0.27%',
  '20.626M',
  '20.493M',
  '12.163B',
  '7.59',
  '+8.19%',
  7.85,
  12.19],
 ['CCL',
  'Carnival Corporation & plc',
  28.01,
  '-0.52',
  '-1.82%',
  '20.364M',
  '20.992M',
  '38.798B',
  '14.43',
  '+36.70%',
  15.07,
  34.03],
 ['TTD',
  'The Trade Desk, Inc.',
  25.17,
  '+0.17',
  '+0.68%',
  '20.32M',
  '15.338M',
  '12.307B',
  '27.02',
  '-61.27%',
  21.08,
  91.45],
 ['RIOT',
  'Riot Platforms, Inc.',
  16.53,
  '+1.24',
  '+8.11%',
  '20.037M',
  '18.317M',
  '6.146B',
  '--',
  '+103.70%',
  6.19,
  23.94],
 ['LYFT',
  'Lyft, Inc.',
  13.84,
  '+0.63',
  '+4.77%',
  '19.877M',
  '15.313M',
  '5.527B',
  '1.98',
  '+14.57%',
  9.66,
  25.54],
 ['VZ',
  'Verizon Communications Inc.',
  51.2,
  '+0.33',
  '+0.65%',
  '19.357M',
  '31.342M',
  '215.945B',
  '12.31',
  '+15.76%',
  38.39,
  51.41],
 ['ASTS',
  'AST SpaceMobile, Inc.',
  104.89,
  '+12.21',
  '+13.17%',
  '19.286M',
  '16M',
  '39.868B',
  '--',
  '+225.95%',
  18.22,
  129.89],
 ['AES',
  'The AES Corporation',
  14.29,
  '+0.11',
  '+0.78%',
  '19.279M',
  '11.032M',
  '10.176B',
  '10.85',
  '+31.46%',
  9.46,
  17.65],
 ['SOUN',
  'SoundHound AI, Inc.',
  8.16,
  '-0.35',
  '-4.11%',
  '18.837M',
  '25.424M',
  '3.428B',
  '--',
  '-14.55%',
  6.52,
  22.17],
 ['PBR',
  'Petróleo Brasileiro S.A. - Petrobras',
  16.77,
  '-0.19',
  '-1.12%',
  '18.833M',
  '23.055M',
  '108.072B',
  '6.84',
  '+30.51%',
  11.03,
  17.34],
 ['HIMS',
  'Hims & Hers Health, Inc.',
  16.45,
  '+0.63',
  '+3.98%',
  '18.799M',
  '23.368M',
  '3.75B',
  '32.17',
  '-52.17%',
  13.74,
  70.43],
 ['AUR',
  'Aurora Innovation, Inc.',
  4.49,
  '-0.11',
  '-2.39%',
  '18.655M',
  '16.673M',
  '8.75B',
  '--',
  '-35.49%',
  3.6,
  8.25],
 ['BTE',
  'Baytex Energy Corp.',
  3.98,
  '+0.12',
  '+3.11%',
  '18.226M',
  '17.831M',
  '3.063B',
  '19.26',
  '+102.03%',
  1.36,
  4.07],
 ['INFY',
  'Infosys Limited',
  14.33,
  '+0.11',
  '+0.77%',
  '18.147M',
  '16.569M',
  '58.83B',
  '18.14',
  '-27.44%',
  13.66,
  30.0],
 ['BTG',
  'B2Gold Corp.',
  5.47,
  '-0.02',
  '-0.36%',
  '17.996M',
  '40.047M',
  '7.314B',
  '21.62',
  '+99.64%',
  2.53,
  6.29],
 ['SLB',
  'SLB N.V.',
  47.89,
  '-0.69',
  '-1.42%',
  '17.819M',
  '18.651M',
  '71.611B',
  '21.82',
  '+20.45%',
  31.11,
  52.45],
 ['QBTS',
  'D-Wave Quantum Inc.',
  18.91,
  '+0.67',
  '+3.67%',
  '17.436M',
  '32.639M',
  '6.993B',
  '--',
  '+261.57%',
  4.49,
  46.75],
 ['DKNG',
  'DraftKings Inc.',
  25.43,
  '+0.98',
  '+4.01%',
  '16.948M',
  '14.053M',
  '12.658B',
  '--',
  '-36.58%',
  21.01,
  48.78],
 ['SMR',
  'NuScale Power Corporation',
  12.54,
  '+0.01',
  '+0.08%',
  '16.695M',
  '26.47M',
  '3.547B',
  '--',
  '-21.38%',
  11.08,
  57.42],
 ['BF-B',
  'Brown-Forman Corporation',
  26.26,
  '-1.87',
  '-6.65%',
  '16.534M',
  '5.284M',
  '12.164B',
  '--',
  '-26.61%',
  25.16,
  38.85],
 ['ABEV',
  'Ambev S.A.',
  2.98,
  '+0.04',
  '+1.36%',
  '16.422M',
  '26.459M',
  '46.537B',
  '16.10',
  '+34.84%',
  2.1,
  3.24],
 ['WMT',
  'Walmart Inc.',
  127.81,
  '-0.10',
  '-0.08%',
  '16.398M',
  '31.048M',
  '1.019T',
  '39.43',
  '+35.05%',
  79.81,
  134.69],
 ['PCG',
  'PG&E Corporation',
  18.88,
  '-0.04',
  '-0.21%',
  '16.221M',
  '20.929M',
  '41.498B',
  '16.19',
  '+17.41%',
  12.97,
  19.16],
 ['JD',
  'JD.com, Inc.',
  25.4,
  '-0.24',
  '-0.94%',
  '16.109M',
  '9.094M',
  '37.475B',
  '8.52',
  '-42.17%',
  25.02,
  46.45],
 ['APLD',
  'Applied Digital Corporation',
  28.65,
  '+2.50',
  '+9.56%',
  '16.043M',
  '29.948M',
  '8.01B',
  '--',
  '+309.29%',
  3.31,
  42.27],
 ['RKLB',
  'Rocket Lab Corporation',
  71.91,
  '+1.78',
  '+2.54%',
  '15.957M',
  '24.048M',
  '38.411B',
  '--',
  '+275.83%',
  14.71,
  99.58],
 ['NOW',
  'ServiceNow, Inc.',
  113.86,
  '+0.67',
  '+0.59%',
  '15.865M',
  '17.175M',
  '120.139B',
  '65.52',
  '-34.34%',
  98.0,
  211.48],
 ['LYG',
  'Lloyds Banking Group plc',
  5.37,
  '+0.05',
  '+0.94%',
  '15.861M',
  '13.806M',
  '96.745B',
  '14.48',
  '+41.69%',
  3.27,
  6.34],
 ['IONQ',
  'IonQ, Inc.',
  37.13,
  '+0.08',
  '+0.22%',
  '15.57M',
  '20.871M',
  '13.652B',
  '--',
  '+81.30%',
  17.88,
  84.64],
 ['WIT',
  'Wipro Limited',
  2.2,
  '0.00',
  '0.00%',
  '15.497M',
  '9.467M',
  '23.259B',
  '15.73',
  '-32.93%',
  2.11,
  3.32],
 ['ORCL',
  'Oracle Corporation',
  152.37,
  '+3.36',
  '+2.25%',
  '15.487M',
  '28.814M',
  '437.925B',
  '28.02',
  '+0.95%',
  118.86,
  345.72],
 ['GGB',
  'Gerdau S.A.',
  3.75,
  '+0.05',
  '+1.35%',
  '15.439M',
  '17.855M',
  '7.407B',
  '30.18',
  '+27.12%',
  2.27,
  4.66],
 ['CDE',
  'Coeur Mining, Inc.',
  23.76,
  '-0.36',
  '-1.49%',
  '15.393M',
  '23.975M',
  '15.256B',
  '28.36',
  '+332.00%',
  4.58,
  27.77],
 ['RUN',
  'Sunrun Inc.',
  12.17,
  '+0.63',
  '+5.46%',
  '15.391M',
  '8.655M',
  '2.824B',
  '7.36',
  '+77.15%',
  5.38,
  22.44],
 ['CSCO',
  'Cisco Systems, Inc.',
  80.87,
  '+1.91',
  '+2.42%',
  '15.299M',
  '22.884M',
  '319.525B',
  '28.57',
  '+27.54%',
  52.11,
  88.19]]

In [77]:
webpage2=requests.get('https://finance.yahoo.com/markets/stocks/most-active/?start=100&count=100',headers=headers).text

In [78]:
soup2=BeautifulSoup(webpage2,'lxml')
table2=soup2.find('table')
tbody2=table2.find('tbody')
for i in range(0,100):
    tr_list=tbody2.find_all('tr')[i].find_all('td')
    l=[tr_list[0].text.strip(),tr_list[1].text.strip(),float(tr_list[3].text.strip().split()[0]),tr_list[4].text.strip(),tr_list[5].text.strip(),tr_list[6].text.strip(),tr_list[7].text.strip(),tr_list[8].text.strip(),tr_list[9].text.strip(),tr_list[10].text.strip()]
    l.extend(tr_list[11].text.strip().split())
    l[-1]=float(l[-1])
    l[-2]=float(l[-2])
    twoD.append(l)

In [79]:
len(twoD)

200

In [81]:
twoD[100:]

[['UBER',
  'Uber Technologies, Inc.',
  76.65,
  '+0.29',
  '+0.38%',
  '15.13M',
  '21.303M',
  '159.266B',
  '16.07',
  '+2.25%',
  60.63,
  101.99],
 ['SNDK',
  'Sandisk Corporation',
  599.06,
  '+33.65',
  '+5.95%',
  '15.109M',
  '16.283M',
  '88.422B',
  '--',
  '+1,188.30%',
  27.89,
  725.0],
 ['PR',
  'Permian Resources Corporation',
  18.53,
  '+0.14',
  '+0.76%',
  '15.011M',
  '11.096M',
  '13.803B',
  '14.69',
  '+48.95%',
  10.01,
  19.38],
 ['GOOG',
  'Alphabet Inc.',
  303.45,
  '-0.11',
  '-0.04%',
  '14.486M',
  '21.864M',
  '3.671T',
  '28.38',
  '+74.19%',
  142.66,
  350.15],
 ['U',
  'Unity Software Inc.',
  20.38,
  '+0.36',
  '+1.80%',
  '14.293M',
  '15.764M',
  '8.824B',
  '--',
  '-12.00%',
  15.33,
  52.15],
 ['FCX',
  'Freeport-McMoRan Inc.',
  65.93,
  '+0.36',
  '+0.55%',
  '14.277M',
  '19.609M',
  '94.755B',
  '44.93',
  '+74.97%',
  27.66,
  69.75],
 ['HL',
  'Hecla Mining Company',
  21.76,
  '+0.06',
  '+0.28%',
  '14.211M',
  '26.801M',
  '14.587B',
  '50.27',
  '+301.48%',
  4.46,
  34.17],
 ['XOM',
  'Exxon Mobil Corporation',
  149.82,
  '-2.01',
  '-1.32%',
  '14.176M',
  '19.842M',
  '624.265B',
  '23.02',
  '+39.21%',
  97.8,
  159.61],
 ['AG',
  'First Majestic Silver Corp.',
  28.65,
  '+0.28',
  '+0.99%',
  '14.165M',
  '25.632M',
  '14.128B',
  '92.64',
  '+390.58%',
  5.19,
  32.04],
 ['AA',
  'Alcoa Corporation',
  61.55,
  '-2.29',
  '-3.59%',
  '13.908M',
  '7.58M',
  '15.939B',
  '14.66',
  '+87.48%',
  21.53,
  68.4],
 ['QS',
  'QuantumScape Corporation',
  7.0,
  '+0.46',
  '+7.03%',
  '13.834M',
  '15.353M',
  '4.209B',
  '--',
  '+60.18%',
  3.4,
  19.07],
 ['CLF',
  'Cleveland-Cliffs Inc.',
  10.83,
  '-0.25',
  '-2.26%',
  '13.633M',
  '16.619M',
  '6.177B',
  '--',
  '+7.65%',
  5.63,
  16.7],
 ['JOBY',
  'Joby Aviation, Inc.',
  9.89,
  '+0.13',
  '+1.33%',
  '13.585M',
  '25.551M',
  '9.54B',
  '--',
  '+48.95%',
  4.96,
  20.95],
 ['KO',
  'The Coca-Cola Company',
  78.1,
  '-1.24',
  '-1.56%',
  '13.53M',
  '18.359M',
  '335.956B',
  '26.39',
  '+10.84%',
  65.35,
  82.0],
 ['STLA',
  'Stellantis N.V.',
  7.47,
  '-0.02',
  '-0.27%',
  '13.321M',
  '14.898M',
  '21.579B',
  '--',
  '-41.41%',
  7.03,
  13.09],
 ['BABA',
  'Alibaba Group Holding Limited',
  133.27,
  '-2.32',
  '-1.71%',
  '13.319M',
  '11.002M',
  '318.159B',
  '18.76',
  '-4.77%',
  95.73,
  192.67],
 ['NKE',
  'NIKE, Inc.',
  58.64,
  '-0.75',
  '-1.26%',
  '13.306M',
  '18.788M',
  '86.81B',
  '35.77',
  '-24.54%',
  52.28,
  80.19],
 ['KHC',
  'The Kraft Heinz Company',
  24.04,
  '-0.18',
  '-0.74%',
  '13.201M',
  '15.451M',
  '28.457B',
  '--',
  '-23.15%',
  21.99,
  33.35],
 ['OXY',
  'Occidental Petroleum Corporation',
  53.61,
  '-0.07',
  '-0.13%',
  '13.197M',
  '12.15M',
  '52.874B',
  '40.16',
  '+17.28%',
  34.78,
  56.34],
 ['WFC',
  'Wells Fargo & Company',
  83.93,
  '+1.40',
  '+1.70%',
  '13.171M',
  '15.897M',
  '263.463B',
  '15.68',
  '+15.53%',
  58.42,
  97.76],
 ['CVE',
  'Cenovus Energy Inc.',
  22.81,
  '+0.44',
  '+1.97%',
  '13.157M',
  '13.519M',
  '43.034B',
  '14.53',
  '+79.89%',
  10.23,
  23.56],
 ['DOW',
  'Dow Inc.',
  32.34,
  '+1.60',
  '+5.20%',
  '13.138M',
  '12.452M',
  '23.205B',
  '--',
  '-13.62%',
  20.4,
  38.36],
 ['BSX',
  'Boston Scientific Corporation',
  72.21,
  '-1.64',
  '-2.22%',
  '13.077M',
  '14.486M',
  '107.151B',
  '39.29',
  '-28.36%',
  71.83,
  109.5],
 ['CPB',
  "The Campbell's Company",
  25.09,
  '-0.96',
  '-3.69%',
  '12.937M',
  '7.278M',
  '7.48B',
  '13.58',
  '-36.94%',
  25.02,
  43.85],
 ['PYPL',
  'PayPal Holdings, Inc.',
  46.75,
  '+0.51',
  '+1.10%',
  '12.903M',
  '23.548M',
  '43.742B',
  '8.43',
  '-31.33%',
  38.46,
  79.5],
 ['HAL',
  'Halliburton Company',
  34.43,
  '-0.66',
  '-1.88%',
  '12.816M',
  '13.03M',
  '28.977B',
  '23.98',
  '+40.82%',
  18.72,
  37.03],
 ['CHWY',
  'Chewy, Inc.',
  25.51,
  '-1.33',
  '-4.96%',
  '12.738M',
  '8.382M',
  '10.587B',
  '55.66',
  '-27.30%',
  23.06,
  48.62],
 ['NVTS',
  'Navitas Semiconductor Corporation',
  9.22,
  '+0.32',
  '+3.60%',
  '12.702M',
  '20.861M',
  '2.125B',
  '--',
  '+270.28%',
  1.52,
  17.79],
 ['PSKY',
  'Paramount Skydance Corporation',
  12.05,
  '-0.40',
  '-3.21%',
  '12.581M',
  '11.064M',
  '13.293B',
  '--',
  '+2.47%',
  9.95,
  20.86],
 ['RITM',
  'Rithm Capital Corp.',
  9.76,
  '-0.19',
  '-1.91%',
  '12.546M',
  '8.756M',
  '5.425B',
  '9.70',
  '-16.72%',
  9.13,
  12.74],
 ['KEY',
  'KeyCorp',
  20.71,
  '+0.24',
  '+1.17%',
  '12.328M',
  '15.958M',
  '22.567B',
  '13.76',
  '+30.01%',
  12.73,
  23.35],
 ['NBIS',
  'Nebius Group N.V.',
  97.78,
  '+10.98',
  '+12.65%',
  '11.986M',
  '12.637M',
  '24.74B',
  '794.04',
  '+264.85%',
  18.31,
  141.1],
 ['SE',
  'Sea Limited',
  88.26,
  '+0.44',
  '+0.50%',
  '11.888M',
  '5.946M',
  '52.252B',
  '41.75',
  '-36.57%',
  77.05,
  199.3],
 ['UUUU',
  'Energy Fuels Inc.',
  21.81,
  '+0.92',
  '+4.40%',
  '11.777M',
  '13.09M',
  '5.252B',
  '--',
  '+420.53%',
  3.2,
  27.9],
 ['UAA',
  'Under Armour, Inc.',
  6.82,
  '-0.30',
  '-4.21%',
  '11.4M',
  '12.471M',
  '2.905B',
  '--',
  '-1.16%',
  4.13,
  8.15],
 ['GLW',
  'Corning Incorporated',
  144.84,
  '-2.73',
  '-1.85%',
  '11.34M',
  '9.225M',
  '124.265B',
  '86.26',
  '+218.26%',
  37.31,
  162.1],
 ['SHOP',
  'Shopify Inc.',
  129.65,
  '+7.78',
  '+6.38%',
  '11.321M',
  '11.037M',
  '169.204B',
  '127.00',
  '+26.50%',
  69.84,
  182.19],
 ['NGD',
  'New Gold Inc.',
  11.78,
  '-0.13',
  '-1.09%',
  '11.179M',
  '19.133M',
  '9.359B',
  '42.26',
  '+317.73%',
  2.73,
  13.63],
 ['AXTI',
  'AXT, Inc.',
  39.13,
  '-2.63',
  '-6.30%',
  '11.101M',
  '7.16M',
  '2.163B',
  '--',
  '+2,424.52%',
  1.13,
  47.03],
 ['EXC',
  'Exelon Corporation',
  49.25,
  '+0.28',
  '+0.58%',
  '10.954M',
  '8.027M',
  '50.377B',
  '18.01',
  '+14.86%',
  41.71,
  49.88],
 ['HPQ',
  'HP Inc.',
  19.18,
  '+0.17',
  '+0.89%',
  '10.92M',
  '17.764M',
  '17.607B',
  '7.08',
  '-36.00%',
  17.56,
  30.61],
 ['CPRT',
  'Copart, Inc.',
  37.94,
  '-0.54',
  '-1.40%',
  '10.892M',
  '9.294M',
  '36.727B',
  '24.09',
  '-29.39%',
  33.81,
  63.85],
 ['FIG',
  'Figma, Inc.',
  29.64,
  '-1.10',
  '-3.58%',
  '10.857M',
  '12.108M',
  '15.464B',
  '--',
  '-74.34%',
  19.85,
  142.92],
 ['SSRM',
  'SSR Mining Inc.',
  33.26,
  '+4.33',
  '+14.97%',
  '10.757M',
  '3.788M',
  '6.763B',
  '17.26',
  '+227.68%',
  8.65,
  33.49],
 ['DVN',
  'Devon Energy Corporation',
  43.49,
  '-0.51',
  '-1.16%',
  '10.732M',
  '10.234M',
  '26.975B',
  '10.78',
  '+28.40%',
  25.89,
  46.15],
 ['BBWI',
  'Bath & Body Works, Inc.',
  23.01,
  '+0.58',
  '+2.59%',
  '10.728M',
  '5.517M',
  '4.744B',
  '6.68',
  '-32.72%',
  14.28,
  35.21],
 ['ET',
  'Energy Transfer LP',
  18.76,
  '-0.10',
  '-0.53%',
  '10.715M',
  '15.238M',
  '64.54B',
  '15.79',
  '+5.99%',
  14.6,
  19.3],
 ['PSLV',
  'Sprott Physical Silver Trust',
  27.22,
  '+0.10',
  '+0.37%',
  '10.65M',
  '23.752M',
  '17.36B',
  '--',
  '+145.23%',
  9.97,
  38.13],
 ['TOST',
  'Toast, Inc.',
  29.47,
  '+0.36',
  '+1.24%',
  '10.606M',
  '10.463M',
  '17.358B',
  '49.37',
  '-13.63%',
  24.35,
  49.66],
 ['MRVL',
  'Marvell Technology, Inc.',
  78.09,
  '+0.58',
  '+0.75%',
  '10.605M',
  '14.311M',
  '68.208B',
  '28.45',
  '+8.04%',
  47.09,
  102.77],
 ['UWMC',
  'UWM Holdings Corporation',
  4.18,
  '-0.07',
  '-1.65%',
  '10.569M',
  '17.34M',
  '6.715B',
  '35.64',
  '-32.91%',
  3.79,
  7.14],
 ['ADT',
  'ADT Inc.',
  6.84,
  '-0.01',
  '-0.15%',
  '10.366M',
  '9.361M',
  '5.609B',
  '10.41',
  '-11.17%',
  6.65,
  8.94],
 ['MOS',
  'The Mosaic Company',
  26.01,
  '-0.77',
  '-2.88%',
  '10.265M',
  '7.265M',
  '8.256B',
  '16.18',
  '+5.22%',
  22.36,
  38.23],
 ['UPS',
  'United Parcel Service, Inc.',
  110.5,
  '-2.73',
  '-2.41%',
  '10.181M',
  '6.031M',
  '93.826B',
  '17.44',
  '-8.30%',
  82.0,
  123.7],
 ['AAOI',
  'Applied Optoelectronics, Inc.',
  99.71,
  '+4.37',
  '+4.58%',
  '10.058M',
  '6.219M',
  '6.808B',
  '--',
  '+541.22%',
  9.71,
  110.0],
 ['STM',
  'STMicroelectronics N.V.',
  33.33,
  '+1.71',
  '+5.41%',
  '10.046M',
  '7.114M',
  '30.1B',
  '181.85',
  '+28.64%',
  17.25,
  35.07],
 ['CRM',
  'Salesforce, Inc.',
  193.08,
  '-2.97',
  '-1.51%',
  '10.018M',
  '10.913M',
  '183.812B',
  '24.74',
  '-32.50%',
  174.57,
  298.08],
 ['TSM',
  'Taiwan Semiconductor Manufacturing Company Limited',
  357.44,
  '+4.31',
  '+1.22%',
  '10.013M',
  '13.045M',
  '1.854T',
  '29.81',
  '+103.26%',
  134.25,
  390.21],
 ['COHR',
  'Coherent Corp.',
  274.86,
  '-5.95',
  '-2.12%',
  '9.998M',
  '5.374M',
  '51.531B',
  '246.58',
  '+322.60%',
  45.58,
  300.2],
 ['BTSG',
  'BrightSpring Health Services, Inc.',
  41.96,
  '+1.31',
  '+3.22%',
  '9.846M',
  '2.05M',
  '7.568B',
  '86.62',
  '+143.53%',
  15.48,
  44.87],
 ['ASX',
  'ASE Technology Holding Co., Ltd.',
  22.1,
  '-0.21',
  '-0.94%',
  '9.83M',
  '7.85M',
  '48.334B',
  '41.68',
  '+123.23%',
  6.94,
  25.29],
 ['CORZ',
  'Core Scientific, Inc.',
  15.84,
  '+0.54',
  '+3.53%',
  '9.784M',
  '11.262M',
  '4.911B',
  '--',
  '+101.78%',
  6.2,
  23.63],
 ['BE',
  'Bloom Energy Corporation',
  164.78,
  '+11.76',
  '+7.69%',
  '9.777M',
  '11.561M',
  '46.229B',
  '--',
  '+635.95%',
  15.15,
  180.9],
 ['BMY',
  'Bristol-Myers Squibb Company',
  62.33,
  '+1.11',
  '+1.81%',
  '9.61M',
  '14.061M',
  '126.933B',
  '18.02',
  '+3.57%',
  42.52,
  63.33],
 ['ROIV',
  'Roivant Sciences Ltd.',
  29.52,
  '+1.67',
  '+6.00%',
  '9.607M',
  '7.126M',
  '21.127B',
  '--',
  '+178.49%',
  8.73,
  29.83],
 ['USAR',
  'USA Rare Earth, Inc.',
  18.91,
  '-0.51',
  '-2.63%',
  '9.565M',
  '18.395M',
  '4.121B',
  '--',
  '+76.73%',
  5.56,
  43.98],
 ['BKR',
  'Baker Hughes Company',
  60.88,
  '-1.66',
  '-2.65%',
  '9.449M',
  '8.935M',
  '60.164B',
  '24.93',
  '+45.30%',
  33.6,
  67.0],
 ['OSCR',
  'Oscar Health, Inc.',
  15.05,
  '+1.38',
  '+10.10%',
  '9.424M',
  '8.471M',
  '4.481B',
  '--',
  '-3.65%',
  11.2,
  23.8],
 ['CCC',
  'CCC Intelligent Solutions Holdings Inc.',
  5.97,
  '+0.32',
  '+5.66%',
  '9.374M',
  '11.744M',
  '3.825B',
  '8,926.28',
  '-36.15%',
  4.81,
  10.5],
 ['TEVA',
  'Teva Pharmaceutical Industries Limited',
  32.91,
  '+0.63',
  '+1.95%',
  '9.321M',
  '9.374M',
  '38.328B',
  '27.91',
  '+114.40%',
  12.47,
  37.35],
 ['FSLY',
  'Fastly, Inc.',
  20.04,
  '-1.10',
  '-5.18%',
  '9.29M',
  '9.112M',
  '3.042B',
  '--',
  '+208.31%',
  4.65,
  21.75],
 ['APH',
  'Amphenol Corporation',
  132.75,
  '+3.17',
  '+2.45%',
  '9.242M',
  '9.713M',
  '163.178B',
  '40.47',
  '+114.98%',
  56.45,
  167.04],
 ['DAL',
  'Delta Air Lines, Inc.',
  63.83,
  '-0.77',
  '-1.19%',
  '9.234M',
  '8.157M',
  '41.689B',
  '8.39',
  '+16.14%',
  34.74,
  76.39],
 ['ZETA',
  'Zeta Global Holdings Corp.',
  18.76,
  '+0.72',
  '+3.99%',
  '9.21M',
  '8.703M',
  '4.613B',
  '--',
  '+16.88%',
  10.69,
  24.9],
 ['CVX',
  'Chevron Corporation',
  186.03,
  '-2.74',
  '-1.45%',
  '9.169M',
  '10.884M',
  '371.94B',
  '28.60',
  '+21.63%',
  132.04,
  191.56],
 ['M',
  "Macy's, Inc.",
  19.21,
  '+0.93',
  '+5.09%',
  '9.156M',
  '6.62M',
  '5.108B',
  '10.98',
  '+45.31%',
  9.76,
  24.41],
 ['C',
  'Citigroup Inc.',
  111.32,
  '+0.56',
  '+0.51%',
  '9.153M',
  '14.796M',
  '280.148B',
  '15.94',
  '+57.72%',
  55.51,
  125.16],
 ['KMI',
  'Kinder Morgan, Inc.',
  33.92,
  '-0.04',
  '-0.12%',
  '9.149M',
  '13.539M',
  '75.465B',
  '24.78',
  '+28.92%',
  23.94,
  34.24],
 ['XYZ',
  'Block, Inc.',
  65.24,
  '+2.34',
  '+3.72%',
  '9.11M',
  '8.052M',
  '39.769B',
  '30.65',
  '+9.10%',
  44.27,
  82.5],
 ['CELH',
  'Celsius Holdings, Inc.',
  45.57,
  '-1.54',
  '-3.27%',
  '9.1M',
  '4.938M',
  '11.747B',
  '196.48',
  '+79.27%',
  25.07,
  66.74],
 ['KDP',
  'Keurig Dr Pepper Inc.',
  28.87,
  '-0.70',
  '-2.37%',
  '9.095M',
  '11.743M',
  '39.225B',
  '19.59',
  '-13.90%',
  25.03,
  36.12],
 ['WDC',
  'Western Digital Corporation',
  261.3,
  '+10.69',
  '+4.27%',
  '9.048M',
  '9.656M',
  '89.338B',
  '25.25',
  '+530.40%',
  28.83,
  309.9],
 ['NRG',
  'NRG Energy, Inc.',
  163.54,
  '+1.48',
  '+0.91%',
  '9.035M',
  '2.312M',
  '35.108B',
  '43.79',
  '+79.44%',
  79.57,
  189.96],
 ['CMG',
  'Chipotle Mexican Grill, Inc.',
  36.71,
  '-0.22',
  '-0.60%',
  '9.032M',
  '17.762M',
  '48.541B',
  '32.18',
  '-28.68%',
  29.75,
  58.42],
 ['CAG',
  'Conagra Brands, Inc.',
  18.85,
  '-0.11',
  '-0.58%',
  '9.002M',
  '12.303M',
  '9.017B',
  '--',
  '-27.44%',
  15.96,
  28.52],
 ['HST',
  'Host Hotels & Resorts, Inc.',
  20.12,
  '+0.52',
  '+2.65%',
  '8.913M',
  '8.24M',
  '14.017B',
  '17.91',
  '+27.34%',
  12.22,
  21.0],
 ['PTEN',
  'Patterson-UTI Energy, Inc.',
  8.87,
  '+0.04',
  '+0.45%',
  '8.867M',
  '10.176M',
  '3.367B',
  '--',
  '+24.06%',
  5.1,
  9.03],
 ['PBR-A',
  'Petróleo Brasileiro S.A. - Petrobras',
  15.49,
  '-0.10',
  '-0.64%',
  '8.792M',
  '9.483M',
  '104.044B',
  '6.84',
  '+30.39%',
  10.28,
  15.94],
 ['COMP',
  'Compass, Inc.',
  9.49,
  '-0.30',
  '-3.06%',
  '8.784M',
  '19.836M',
  '6.874B',
  '--',
  '+9.08%',
  5.66,
  13.96],
 ['RF',
  'Regions Financial Corporation',
  27.83,
  '+0.09',
  '+0.32%',
  '8.775M',
  '13.472M',
  '24.403B',
  '12.16',
  '+26.79%',
  17.74,
  31.53],
 ['LRCX',
  'Lam Research Corporation',
  222.99,
  '+5.98',
  '+2.76%',
  '8.58M',
  '11.761M',
  '280.082B',
  '47.41',
  '+191.60%',
  56.32,
  256.68],
 ['GLXY',
  'Galaxy Digital',
  24.34,
  '+3.66',
  '+17.70%',
  '8.547M',
  '6.757M',
  '9.519B',
  '--',
  '+6.75%',
  16.67,
  45.92],
 ['CFLT',
  'Confluent, Inc.',
  30.75,
  '0.00',
  '0.00%',
  '8.501M',
  '16.472M',
  '10.998B',
  '--',
  '+7.33%',
  15.64,
  31.22],
 ['B',
  'Barrick Mining Corporation',
  46.77,
  '+0.42',
  '+0.91%',
  '8.449M',
  '15.115M',
  '78.357B',
  '17.25',
  '+153.36%',
  17.0,
  54.69],
 ['STNE',
  'StoneCo Ltd.',
  14.29,
  '+0.56',
  '+4.08%',
  '8.427M',
  '5.462M',
  '3.823B',
  '--',
  '+50.26%',
  8.95,
  19.95],
 ['BCS',
  'Barclays PLC',
  23.34,
  '+0.27',
  '+1.17%',
  '8.407M',
  '6.383M',
  '81.45B',
  '10.34',
  '+45.69%',
  12.14,
  27.7],
 ['ONON',
  'On Holding AG',
  43.23,
  '-0.68',
  '-1.55%',
  '8.325M',
  '5.026M',
  '14.273B',
  '53.08',
  '-12.72%',
  34.38,
  61.29],
 ['MO',
  'Altria Group, Inc.',
  68.12,
  '-0.77',
  '-1.12%',
  '8.308M',
  '10.03M',
  '114.351B',
  '16.69',
  '+19.49%',
  52.82,
  70.51],
 ['MDLZ',
  'Mondelez International, Inc.',
  58.69,
  '-0.08',
  '-0.14%',
  '8.297M',
  '11.563M',
  '75.731B',
  '31.98',
  '-12.09%',
  51.2,
  71.15],
 ['CRWD',
  'CrowdStrike Holdings, Inc.',
  407.68,
  '+16.26',
  '+4.15%',
  '8.296M',
  '3.45M',
  '102.775B',
  '--',
  '+17.24%',
  298.0,
  566.9]]

In [82]:
webpage3=requests.get('https://finance.yahoo.com/markets/stocks/most-active/?start=200&count=100',headers=headers).text
soup3=BeautifulSoup(webpage3,'lxml')
table3=soup3.find('table')
tbody3=table3.find('tbody')
for i in range(0,100):
    tr_list=tbody3.find_all('tr')[i].find_all('td')
    l=[tr_list[0].text.strip(),tr_list[1].text.strip(),float(tr_list[3].text.strip().split()[0]),tr_list[4].text.strip(),tr_list[5].text.strip(),tr_list[6].text.strip(),tr_list[7].text.strip(),tr_list[8].text.strip(),tr_list[9].text.strip(),tr_list[10].text.strip()]
    l.extend(tr_list[11].text.strip().split())
    l[-1]=float(l[-1])
    l[-2]=float(l[-2])
    twoD.append(l)

In [83]:
len(twoD)

300

In [85]:
twoD[200:]

[['AEO',
  'American Eagle Outfitters, Inc.',
  22.45,
  '+0.21',
  '+0.94%',
  '8.294M',
  '6.154M',
  '3.806B',
  '19.45',
  '+82.37%',
  9.27,
  28.46],
 ['APP',
  'AppLovin Corporation',
  482.81,
  '+43.92',
  '+10.01%',
  '8.288M',
  '5.745M',
  '163.168B',
  '43.13',
  '+85.96%',
  200.5,
  745.61],
 ['HPE',
  'Hewlett Packard Enterprise Company',
  21.55,
  '-0.09',
  '-0.42%',
  '8.286M',
  '19.335M',
  '28.759B',
  '--',
  '+19.99%',
  11.97,
  26.44],
 ['META',
  'Meta Platforms, Inc.',
  667.73,
  '+12.65',
  '+1.93%',
  '8.271M',
  '15.272M',
  '1.689T',
  '27.82',
  '+6.34%',
  479.8,
  796.25],
 ['DIS',
  'The Walt Disney Company',
  103.04,
  '-0.26',
  '-0.25%',
  '8.264M',
  '11.694M',
  '182.73B',
  '15.35',
  '-2.27%',
  80.1,
  124.69],
 ['PANW',
  'Palo Alto Networks, Inc.',
  158.56,
  '+2.47',
  '+1.58%',
  '8.078M',
  '9.87M',
  '129.385B',
  '83.38',
  '-11.58%',
  139.57,
  223.61],
 ['TGT',
  'Target Corporation',
  120.08,
  '-0.72',
  '-0.60%',
  '8.036M',
  '6.842M',
  '54.564B',
  '13.92',
  '+5.29%',
  83.44,
  126.0],
 ['CNQ',
  'Canadian Natural Resources Limited',
  44.18,
  '+0.05',
  '+0.11%',
  '8.024M',
  '9.201M',
  '92.095B',
  '19.14',
  '+58.01%',
  24.65,
  45.85],
 ['CRDO',
  'Credo Technology Group Holding Ltd',
  102.54,
  '+5.24',
  '+5.39%',
  '7.956M',
  '6.568M',
  '18.522B',
  '62.66',
  '+143.74%',
  29.09,
  213.8],
 ['AVTR',
  'Avantor, Inc.',
  8.65,
  '-0.13',
  '-1.48%',
  '7.946M',
  '12.095M',
  '5.9B',
  '--',
  '-46.51%',
  8.43,
  18.02],
 ['WBS',
  'Webster Financial Corporation',
  70.1,
  '+1.33',
  '+1.93%',
  '7.914M',
  '3.546M',
  '11.303B',
  '12.10',
  '+35.56%',
  39.43,
  74.0],
 ['PL',
  'Planet Labs PBC',
  26.0,
  '+0.70',
  '+2.77%',
  '7.834M',
  '13.123M',
  '8.868B',
  '--',
  '+554.91%',
  2.79,
  30.9],
 ['COP',
  'ConocoPhillips',
  115.65,
  '-2.87',
  '-2.42%',
  '7.695M',
  '8.556M',
  '141.364B',
  '18.62',
  '+30.53%',
  79.88,
  122.5],
 ['FSK',
  'FS KKR Capital Corp.',
  11.01,
  '+0.06',
  '+0.55%',
  '7.559M',
  '3.4M',
  '3.084B',
  '274.98',
  '-50.54%',
  10.28,
  22.95],
 ['LITE',
  'Lumentum Holdings Inc.',
  680.8,
  '-13.63',
  '-1.96%',
  '7.552M',
  '4.784M',
  '48.609B',
  '239.44',
  '+1,014.42%',
  45.65,
  783.8],
 ['ON',
  'ON Semiconductor Corporation',
  62.53,
  '-0.89',
  '-1.40%',
  '7.49M',
  '9.17M',
  '25.161B',
  '229.24',
  '+42.50%',
  31.04,
  73.76],
 ['QXO',
  'QXO, Inc.',
  23.26,
  '+1.31',
  '+5.97%',
  '7.466M',
  '8.027M',
  '16.48B',
  '--',
  '+77.29%',
  11.97,
  27.61],
 ['QCOM',
  'QUALCOMM Incorporated',
  139.51,
  '+1.38',
  '+1.00%',
  '7.452M',
  '9.63M',
  '149.003B',
  '28.72',
  '-10.59%',
  120.8,
  205.95],
 ['INVH',
  'Invitation Homes Inc.',
  26.83,
  '+0.55',
  '+2.09%',
  '7.434M',
  '6.782M',
  '16.447B',
  '27.31',
  '-20.60%',
  25.21,
  35.8],
 ['KKR',
  'KKR & Co. Inc.',
  93.83,
  '+3.28',
  '+3.62%',
  '7.409M',
  '6.764M',
  '86.888B',
  '38.72',
  '-19.20%',
  84.52,
  153.87],
 ['LYB',
  'LyondellBasell Industries N.V.',
  61.92,
  '+3.71',
  '+6.37%',
  '7.38M',
  '6.31M',
  '19.949B',
  '--',
  '-18.43%',
  41.58,
  78.41],
 ['DELL',
  'Dell Technologies Inc.',
  147.1,
  '+1.92',
  '+1.32%',
  '7.36M',
  '7.581M',
  '98.586B',
  '17.69',
  '+58.14%',
  66.25,
  168.08],
 ['BAX',
  'Baxter International Inc.',
  19.03,
  '0.00',
  '0.00%',
  '7.345M',
  '9.553M',
  '9.791B',
  '--',
  '-46.30%',
  17.4,
  37.74],
 ['VNET',
  'VNET Group, Inc.',
  10.26,
  '+0.40',
  '+4.06%',
  '7.27M',
  '5.94M',
  '2.76B',
  '--',
  '-15.00%',
  4.65,
  14.48],
 ['ARCC',
  'Ares Capital Corporation',
  19.13,
  '+0.18',
  '+0.95%',
  '7.266M',
  '6.61M',
  '13.736B',
  '10.21',
  '-14.33%',
  18.17,
  23.42],
 ['ZM',
  'Zoom Communications, Inc.',
  78.02,
  '+4.52',
  '+6.15%',
  '7.238M',
  '3.785M',
  '23.351B',
  '11.76',
  '+3.37%',
  64.41,
  97.58],
 ['BP',
  'BP p.l.c.',
  38.84,
  '-0.02',
  '-0.05%',
  '7.22M',
  '9.24M',
  '99.495B',
  '1,918.30',
  '+22.49%',
  25.22,
  39.56],
 ['FAST',
  'Fastenal Company',
  46.43,
  '+0.20',
  '+0.43%',
  '7.153M',
  '8.483M',
  '53.31B',
  '42.50',
  '+19.28%',
  35.31,
  50.63],
 ['DHT',
  'DHT Holdings, Inc.',
  18.62,
  '-0.64',
  '-3.32%',
  '7.118M',
  '3.155M',
  '2.994B',
  '15.00',
  '+75.66%',
  8.99,
  20.55],
 ['ADMA',
  'ADMA Biologics, Inc.',
  16.54,
  '+0.16',
  '+0.98%',
  '7.116M',
  '2.579M',
  '3.947B',
  '27.63',
  '-2.19%',
  13.76,
  25.67],
 ['BX',
  'Blackstone Inc.',
  114.14,
  '+3.22',
  '+2.90%',
  '7.115M',
  '6.095M',
  '140.351B',
  '29.80',
  '-21.62%',
  105.09,
  190.09],
 ['PPL',
  'PPL Corporation',
  38.59,
  '+0.34',
  '+0.89%',
  '7.074M',
  '8.599M',
  '28.993B',
  '24.36',
  '+13.87%',
  32.5,
  39.09],
 ['NEE',
  'NextEra Energy, Inc.',
  92.6,
  '+0.01',
  '+0.01%',
  '7.064M',
  '10.013M',
  '192.934B',
  '28.09',
  '+32.27%',
  61.72,
  95.91],
 ['GIS',
  'General Mills, Inc.',
  43.56,
  '-0.98',
  '-2.20%',
  '6.984M',
  '7.97M',
  '23.243B',
  '9.75',
  '-29.99%',
  42.79,
  67.35],
 ['S',
  'SentinelOne, Inc.',
  13.49,
  '+0.22',
  '+1.66%',
  '6.972M',
  '8.696M',
  '4.585B',
  '--',
  '-32.21%',
  12.24,
  21.4],
 ['EQX',
  'Equinox Gold Corp.',
  17.15,
  '-0.08',
  '-0.46%',
  '6.932M',
  '10.201M',
  '13.537B',
  '--',
  '+163.85%',
  5.59,
  18.96],
 ['LUMN',
  'Lumen Technologies, Inc.',
  6.96,
  '+0.03',
  '+0.43%',
  '6.929M',
  '13.351M',
  '7.138B',
  '--',
  '+38.37%',
  3.01,
  11.95],
 ['ACI',
  'Albertsons Companies, Inc.',
  17.1,
  '-0.42',
  '-2.40%',
  '6.925M',
  '8.003M',
  '9.393B',
  '11.52',
  '-18.45%',
  15.8,
  23.2],
 ['KR',
  'The Kroger Co.',
  67.99,
  '-0.65',
  '-0.95%',
  '6.912M',
  '6.468M',
  '45.055B',
  '59.50',
  '+6.60%',
  58.6,
  74.9],
 ['VTRS',
  'Viatris Inc.',
  14.71,
  '-0.18',
  '-1.21%',
  '6.849M',
  '9.983M',
  '16.982B',
  '--',
  '+54.68%',
  6.85,
  16.47],
 ['PEP',
  'PepsiCo, Inc.',
  163.92,
  '-0.99',
  '-0.60%',
  '6.832M',
  '8.618M',
  '224.134B',
  '27.88',
  '+6.02%',
  127.6,
  171.48],
 ['EQT',
  'EQT Corporation',
  61.31,
  '-0.30',
  '-0.49%',
  '6.82M',
  '9.905M',
  '38.274B',
  '18.62',
  '+32.82%',
  43.57,
  63.06],
 ['FRMI',
  'Fermi Inc.',
  9.04,
  '-0.23',
  '-2.48%',
  '6.798M',
  '7.776M',
  '5.551B',
  '--',
  '-72.21%',
  7.18,
  36.99],
 ['HLN',
  'Haleon plc',
  10.47,
  '-0.14',
  '-1.32%',
  '6.709M',
  '8.828M',
  '46.624B',
  '21.62',
  '+0.77%',
  8.71,
  11.42],
 ['FNB',
  'F.N.B. Corporation',
  17.06,
  '+0.03',
  '+0.18%',
  '6.708M',
  '6.279M',
  '6.097B',
  '11.04',
  '+23.80%',
  10.88,
  19.14],
 ['KGC',
  'Kinross Gold Corporation',
  33.97,
  '+0.17',
  '+0.50%',
  '6.7M',
  '10.814M',
  '40.989B',
  '18.81',
  '+204.94%',
  10.42,
  39.11],
 ['GAP',
  'The Gap, Inc.',
  27.74,
  '+0.49',
  '+1.80%',
  '6.689M',
  '7.313M',
  '10.317B',
  '12.68',
  '+42.40%',
  16.99,
  29.36],
 ['CNH',
  'CNH Industrial N.V.',
  11.9,
  '-0.16',
  '-1.33%',
  '6.678M',
  '13.012M',
  '14.885B',
  '30.17',
  '-6.37%',
  9.0,
  14.27],
 ['LUV',
  'Southwest Airlines Co.',
  47.15,
  '-0.60',
  '-1.26%',
  '6.643M',
  '10.676M',
  '24.384B',
  '60.94',
  '+59.67%',
  23.82,
  55.11],
 ['UAL',
  'United Airlines Holdings, Inc.',
  100.48,
  '-2.06',
  '-2.01%',
  '6.633M',
  '5.342M',
  '32.529B',
  '10.12',
  '+16.47%',
  52.0,
  119.21],
 ['LUNR',
  'Intuitive Machines, Inc.',
  18.62,
  '+0.42',
  '+2.31%',
  '6.617M',
  '11.304M',
  '2.65B',
  '--',
  '+65.36%',
  6.14,
  23.32],
 ['BOX',
  'Box, Inc.',
  26.35,
  '+2.43',
  '+10.16%',
  '6.579M',
  '2.569M',
  '3.774B',
  '--',
  '-18.07%',
  21.61,
  38.8],
 ['CSX',
  'CSX Corporation',
  42.78,
  '+0.12',
  '+0.28%',
  '6.535M',
  '13.159M',
  '79.552B',
  '28.03',
  '+38.31%',
  26.22,
  43.35],
 ['AFRM',
  'Affirm Holdings, Inc.',
  50.72,
  '+2.89',
  '+6.04%',
  '6.521M',
  '6.347M',
  '16.895B',
  '58.73',
  '-3.65%',
  30.9,
  100.0],
 ['PG',
  'The Procter & Gamble Company',
  158.3,
  '-1.42',
  '-0.89%',
  '6.507M',
  '11.345M',
  '369.905B',
  '24.23',
  '-9.37%',
  137.62,
  179.99],
 ['JPM',
  'JPMorgan Chase & Co.',
  299.39,
  '-0.87',
  '-0.29%',
  '6.488M',
  '10.938M',
  '1.006T',
  '14.86',
  '+21.44%',
  202.16,
  337.25],
 ['ERIC',
  'Telefonaktiebolaget LM Ericsson (publ)',
  11.41,
  '+0.13',
  '+1.15%',
  '6.48M',
  '8.676M',
  '38.367B',
  '12.29',
  '+34.87%',
  6.64,
  11.64],
 ['OBDC',
  'Blue Owl Capital Corporation',
  11.55,
  '+0.05',
  '+0.43%',
  '6.473M',
  '5.698M',
  '5.903B',
  '9.30',
  '-21.64%',
  10.7,
  15.36],
 ['UNH',
  'UnitedHealth Group Incorporated',
  291.96,
  '+2.75',
  '+0.95%',
  '6.463M',
  '8.947M',
  '264.469B',
  '22.29',
  '-40.14%',
  234.6,
  606.36],
 ['UEC',
  'Uranium Energy Corp.',
  15.04,
  '+0.48',
  '+3.30%',
  '6.426M',
  '10.861M',
  '7.27B',
  '--',
  '+196.06%',
  3.85,
  20.34],
 ['EXK',
  'Endeavour Silver Corp.',
  12.42,
  '+0.53',
  '+4.46%',
  '6.419M',
  '14.948M',
  '3.654B',
  '--',
  '+213.64%',
  2.95,
  15.15],
 ['TEAM',
  'Atlassian Corporation',
  76.81,
  '-1.57',
  '-2.00%',
  '6.374M',
  '5.136M',
  '20.258B',
  '--',
  '-69.36%',
  67.85,
  271.46],
 ['NEM',
  'Newmont Corporation',
  119.37,
  '+0.85',
  '+0.72%',
  '6.362M',
  '9.783M',
  '130.264B',
  '15.74',
  '+171.79%',
  42.03,
  134.88],
 ['APA',
  'APA Corporation',
  31.1,
  '-0.75',
  '-2.35%',
  '6.301M',
  '6.364M',
  '11.127B',
  '7.94',
  '+65.87%',
  13.58,
  32.78],
 ['WIX',
  'Wix.com Ltd.',
  83.78,
  '+9.42',
  '+12.67%',
  '6.277M',
  '1.977M',
  '4.665B',
  '30.76',
  '-55.20%',
  60.22,
  195.15],
 ['PBF',
  'PBF Energy Inc.',
  44.8,
  '+5.04',
  '+12.68%',
  '6.25M',
  '3.31M',
  '5.238B',
  '--',
  '+113.23%',
  13.62,
  45.13],
 ['GM',
  'General Motors Company',
  78.6,
  '+1.33',
  '+1.72%',
  '6.247M',
  '8.815M',
  '73.323B',
  '16.98',
  '+66.53%',
  41.6,
  87.62],
 ['VLY',
  'Valley National Bancorp',
  12.58,
  '+0.03',
  '+0.24%',
  '6.243M',
  '7.696M',
  '7.015B',
  '12.68',
  '+39.93%',
  7.48,
  13.87],
 ['FTNT',
  'Fortinet, Inc.',
  82.79,
  '+1.69',
  '+2.08%',
  '6.18M',
  '6.742M',
  '61.567B',
  '32.72',
  '-18.61%',
  70.12,
  109.33],
 ['PHYS',
  'Sprott Physical Gold Trust',
  39.17,
  '+0.35',
  '+0.90%',
  '6.142M',
  '8.079M',
  '18.816B',
  '--',
  '+72.86%',
  22.45,
  42.07],
 ['VISN',
  'Vistance Networks, Inc.',
  17.56,
  '+0.15',
  '+0.86%',
  '6.106M',
  '3.924M',
  '3.89B',
  '16.08',
  '+215.26%',
  2.94,
  20.55],
 ['XPEV',
  'XPeng Inc.',
  16.17,
  '+0.30',
  '+1.89%',
  '6.104M',
  '6.72M',
  '15.709B',
  '--',
  '-27.26%',
  15.38,
  28.24],
 ['BB',
  'BlackBerry Limited',
  3.48,
  '+0.07',
  '+2.05%',
  '6.096M',
  '7.716M',
  '2.054B',
  '94.99',
  '-21.09%',
  2.8,
  5.32],
 ['AR',
  'Antero Resources Corporation',
  37.79,
  '+0.20',
  '+0.53%',
  '6.095M',
  '5.889M',
  '11.659B',
  '18.27',
  '+11.87%',
  29.1,
  44.02],
 ['MNST',
  'Monster Beverage Corporation',
  78.61,
  '-0.38',
  '-0.48%',
  '6.06M',
  '6.05M',
  '76.804B',
  '41.78',
  '+41.16%',
  54.0,
  87.38],
 ['SCHW',
  'The Charles Schwab Corporation',
  96.04,
  '+0.80',
  '+0.84%',
  '6.032M',
  '10.706M',
  '174.334B',
  '20.54',
  '+27.10%',
  65.88,
  107.5],
 ['CX',
  'CEMEX, S.A.B. de C.V.',
  11.94,
  '+0.54',
  '+4.74%',
  '6.029M',
  '6.385M',
  '17.323B',
  '44.97',
  '+87.74%',
  4.89,
  13.35],
 ['MAT',
  'Mattel, Inc.',
  15.84,
  '-0.30',
  '-1.86%',
  '5.953M',
  '5.22M',
  '4.923B',
  '13.23',
  '-23.37%',
  13.95,
  22.48],
 ['HOG',
  'Harley-Davidson, Inc.',
  19.46,
  '+0.97',
  '+5.25%',
  '5.917M',
  '3.376M',
  '2.365B',
  '6.38',
  '-23.57%',
  17.11,
  31.25],
 ['EQNR',
  'Equinor ASA',
  31.58,
  '+0.33',
  '+1.06%',
  '5.895M',
  '4.969M',
  '78.788B',
  '16.35',
  '+41.17%',
  21.41,
  32.58],
 ['TU',
  'TELUS Corporation',
  13.88,
  '+0.17',
  '+1.24%',
  '5.884M',
  '5.759M',
  '21.667B',
  '25.53',
  '-11.14%',
  12.54,
  16.74],
 ['AMAT',
  'Applied Materials, Inc.',
  357.76,
  '+6.44',
  '+1.83%',
  '5.84M',
  '7.579M',
  '283.922B',
  '38.12',
  '+136.08%',
  123.74,
  395.95],
 ['ANET',
  'Arista Networks, Inc.',
  134.83,
  '+10.23',
  '+8.21%',
  '5.814M',
  '7.884M',
  '169.789B',
  '47.02',
  '+59.86%',
  59.43,
  164.94],
 ['MDT',
  'Medtronic plc',
  95.6,
  '-1.11',
  '-1.15%',
  '5.805M',
  '7.731M',
  '122.739B',
  '27.40',
  '+2.65%',
  79.55,
  106.33],
 ['OCUL',
  'Ocular Therapeutix, Inc.',
  11.04,
  '+0.28',
  '+2.60%',
  '5.755M',
  '6.327M',
  '2.403B',
  '--',
  '+50.41%',
  5.8,
  16.44],
 ['ROST',
  'Ross Stores, Inc.',
  213.52,
  '+15.88',
  '+8.03%',
  '5.753M',
  '2.548M',
  '69.442B',
  '31.59',
  '+54.85%',
  122.36,
  216.8],
 ['NLY',
  'Annaly Capital Management, Inc.',
  22.95,
  '-0.09',
  '-0.39%',
  '5.742M',
  '8.265M',
  '16.487B',
  '7.95',
  '+7.70%',
  16.6,
  24.52],
 ['SONY',
  'Sony Group Corporation',
  21.99,
  '+0.41',
  '+1.90%',
  '5.738M',
  '5.957M',
  '131.134B',
  '17.29',
  '-9.88%',
  20.42,
  30.34],
 ['RBLX',
  'Roblox Corporation',
  67.4,
  '+0.43',
  '+0.64%',
  '5.726M',
  '11.452M',
  '47.767B',
  '--',
  '+15.08%',
  50.1,
  150.59],
 ['O',
  'Realty Income Corporation',
  66.0,
  '-0.56',
  '-0.84%',
  '5.695M',
  '6.717M',
  '61.761B',
  '57.90',
  '+15.12%',
  50.71,
  67.94],
 ['GPK',
  'Graphic Packaging Holding Company',
  11.19,
  '-0.09',
  '-0.80%',
  '5.687M',
  '6.144M',
  '3.302B',
  '7.95',
  '-58.09%',
  11.02,
  28.19],
 ['SLM',
  'SLM Corporation',
  19.64,
  '+0.45',
  '+2.34%',
  '5.677M',
  '3.844M',
  '3.892B',
  '5.48',
  '-32.28%',
  17.77,
  34.97],
 ['PRMB',
  'Primo Brands Corporation',
  22.65,
  '-0.36',
  '-1.56%',
  '5.664M',
  '6.291M',
  '8.387B',
  '108.71',
  '-30.05%',
  14.36,
  35.85],
 ['ASB',
  'Associated Banc-Corp',
  26.35,
  '-0.01',
  '-0.04%',
  '5.646M',
  '2.349M',
  '4.374B',
  '9.60',
  '+14.52%',
  18.32,
  29.52],
 ['TMUS',
  'T-Mobile US, Inc.',
  219.71,
  '+1.18',
  '+0.54%',
  '5.62M',
  '6.247M',
  '245.747B',
  '22.23',
  '-16.44%',
  181.36,
  272.6],
 ['NOV',
  'NOV Inc.',
  19.51,
  '+0.07',
  '+0.36%',
  '5.609M',
  '4.519M',
  '7.116B',
  '51.39',
  '+35.96%',
  10.84,
  20.86],
 ['FOLD',
  'Amicus Therapeutics, Inc.',
  14.33,
  '-0.01',
  '-0.07%',
  '5.57M',
  '11.129M',
  '4.5B',
  '--',
  '+58.87%',
  5.51,
  14.38],
 ['SM',
  'SM Energy Company',
  24.54,
  '+0.45',
  '+1.87%',
  '5.566M',
  '5.902M',
  '5.847B',
  '4.29',
  '-9.61%',
  17.45,
  32.26],
 ['FIGR',
  'Figure Technology Solutions, Inc.',
  30.49,
  '+2.02',
  '+7.10%',
  '5.561M',
  '4.304M',
  '6.58B',
  '67.55',
  '-1.99%',
  25.01,
  78.0],
 ['PAGS',
  'PagSeguro Digital Ltd.',
  10.57,
  '+0.56',
  '+5.59%',
  '5.531M',
  '3.858M',
  '3.085B',
  '7.65',
  '+40.00%',
  7.16,
  12.32]]

In [86]:
webpage4=requests.get('https://finance.yahoo.com/markets/stocks/most-active/?start=300&count=100',headers=headers).text
soup4=BeautifulSoup(webpage4,'lxml')
table4=soup4.find('table')
tbody4=table4.find('tbody')
for i in range(0,28):
    tr_list=tbody4.find_all('tr')[i].find_all('td')
    l=[tr_list[0].text.strip(),tr_list[1].text.strip(),float(tr_list[3].text.strip().split()[0]),tr_list[4].text.strip(),tr_list[5].text.strip(),tr_list[6].text.strip(),tr_list[7].text.strip(),tr_list[8].text.strip(),tr_list[9].text.strip(),tr_list[10].text.strip()]
    l.extend(tr_list[11].text.strip().split())
    l[-1]=float(l[-1])
    l[-2]=float(l[-2])
    twoD.append(l)

In [87]:
len(twoD)

328

In [88]:
twoD[300:]

[['SKM',
  'SK Telecom Co., Ltd.',
  31.5,
  '+2.22',
  '+7.58%',
  '5.479M',
  '1.486M',
  '12.088B',
  '43.73',
  '+45.90%',
  19.66,
  33.71],
 ['FISV',
  'Fiserv, Inc.',
  62.6,
  '-0.29',
  '-0.46%',
  '5.475M',
  '9.966M',
  '33.67B',
  '9.76',
  '-71.54%',
  57.79,
  227.0],
 ['GEN',
  'Gen Digital Inc.',
  22.29,
  '-0.11',
  '-0.49%',
  '5.462M',
  '5.897M',
  '13.747B',
  '23.04',
  '-18.44%',
  21.33,
  32.22],
 ['HDB',
  'HDFC Bank Limited',
  30.79,
  '-0.06',
  '-0.19%',
  '5.391M',
  '5.68M',
  '157.946B',
  '18.19',
  '+4.25%',
  29.23,
  39.81],
 ['OKLO',
  'Oklo Inc.',
  65.65,
  '+2.35',
  '+3.71%',
  '5.388M',
  '10.531M',
  '10.258B',
  '--',
  '+152.79%',
  17.42,
  193.84],
 ['DT',
  'Dynatrace, Inc.',
  37.26,
  '+0.22',
  '+0.59%',
  '5.36M',
  '5.556M',
  '11.233B',
  '60.90',
  '-30.46%',
  32.83,
  57.55],
 ['TEM',
  'Tempus AI, Inc.',
  51.29,
  '-0.11',
  '-0.21%',
  '5.356M',
  '5.239M',
  '9.169B',
  '--',
  '+4.97%',
  36.22,
  104.32],
 ['SHEL',
  'Shell plc',
  82.7,
  '+0.37',
  '+0.45%',
  '5.287M',
  '4.779M',
  '235.26B',
  '13.96',
  '+25.28%',
  58.55,
  84.55],
 ['GT',
  'The Goodyear Tire & Rubber Company',
  8.0,
  '+0.09',
  '+1.14%',
  '5.287M',
  '6.479M',
  '2.29B',
  '--',
  '-10.81%',
  6.51,
  12.03],
 ['CVS',
  'CVS Health Corporation',
  80.57,
  '+0.08',
  '+0.10%',
  '5.278M',
  '8.673M',
  '102.502B',
  '58.75',
  '+23.48%',
  58.35,
  85.15],
 ['DOC',
  'Healthpeak Properties, Inc.',
  17.65,
  '+0.16',
  '+0.91%',
  '5.265M',
  '9.29M',
  '12.268B',
  '176.30',
  '-12.32%',
  15.71,
  21.28],
 ['VSNT',
  'Versant Media Group, Inc.',
  36.02,
  '+2.01',
  '+5.91%',
  '5.265M',
  '4.361M',
  '5.206B',
  '--',
  '-21.10%',
  27.17,
  59.0],
 ['IP',
  'International Paper Company',
  42.58,
  '+0.53',
  '+1.26%',
  '5.249M',
  '6.474M',
  '22.484B',
  '--',
  '-17.66%',
  35.56,
  56.64],
 ['USB',
  'U.S. Bancorp',
  54.34,
  '+0.35',
  '+0.65%',
  '5.235M',
  '10.623M',
  '84.428B',
  '11.82',
  '+22.44%',
  35.18,
  61.19],
 ['VICI',
  'VICI Properties Inc.',
  29.89,
  '-0.31',
  '-1.03%',
  '5.233M',
  '11.394M',
  '31.947B',
  '11.63',
  '-6.51%',
  27.48,
  34.03],
 ['KLAR',
  'Klarna Group plc',
  13.57,
  '+0.19',
  '+1.42%',
  '5.195M',
  '4.625M',
  '5.119B',
  '--',
  '-68.25%',
  12.5,
  47.48],
 ['DDOG',
  'Datadog, Inc.',
  118.33,
  '+6.56',
  '+5.87%',
  '5.187M',
  '5.585M',
  '41.72B',
  '362.25',
  '+6.16%',
  81.63,
  201.69],
 ['TFC',
  'Truist Financial Corporation',
  49.11,
  '-0.19',
  '-0.39%',
  '5.162M',
  '9.034M',
  '62.824B',
  '12.97',
  '+16.26%',
  33.56,
  56.2],
 ['FOXA',
  'Fox Corporation',
  58.42,
  '+1.34',
  '+2.35%',
  '5.145M',
  '3.919M',
  '24.852B',
  '13.60',
  '+5.51%',
  46.42,
  76.39],
 ['NWG',
  'NatWest Group plc',
  16.12,
  '+0.16',
  '+1.00%',
  '5.138M',
  '3.048M',
  '63.58B',
  '8.92',
  '+33.11%',
  10.4,
  19.36],
 ['OKTA',
  'Okta, Inc.',
  71.74,
  '-0.78',
  '-1.08%',
  '5.077M',
  '2.896M',
  '12.714B',
  '68.80',
  '-35.50%',
  68.77,
  127.57],
 ['VNOM',
  'Viper Energy, Inc.',
  44.65,
  '-0.13',
  '-0.29%',
  '5.075M',
  '2.708M',
  '16.164B',
  '--',
  '+7.64%',
  34.71,
  48.0],
 ['UMC',
  'United Microelectronics Corporation',
  9.88,
  '-0.02',
  '-0.20%',
  '5.066M',
  '10.514M',
  '24.919B',
  '19.49',
  '+48.35%',
  5.71,
  12.68],
 ['SBSW',
  'Sibanye Stillwater Limited',
  15.1,
  '+0.15',
  '+1.00%',
  '5.065M',
  '7.502M',
  '10.923B',
  '--',
  '+303.74%',
  3.18,
  21.29],
 ['MRK',
  'Merck & Co., Inc.',
  120.28,
  '+0.45',
  '+0.38%',
  '5.055M',
  '13.217M',
  '297.379B',
  '16.68',
  '+27.96%',
  73.31,
  125.14],
 ['MCHP',
  'Microchip Technology Incorporated',
  69.9,
  '-1.49',
  '-2.09%',
  '5.044M',
  '8.814M',
  '37.825B',
  '--',
  '+19.98%',
  34.13,
  83.35],
 ['CRBG',
  'Corebridge Financial, Inc.',
  26.45,
  '+1.35',
  '+5.38%',
  '5.036M',
  '5.054M',
  '13.341B',
  '--',
  '-17.52%',
  23.69,
  36.57],
 ['FRO',
  'Frontline plc',
  36.28,
  '-0.86',
  '-2.32%',
  '5.012M',
  '3.364M',
  '8.077B',
  '23.27',
  '+124.09%',
  12.4,
  39.89]]

In [89]:
pd.DataFrame(twoD)

,0,1,2,3,4,5,6,7,8,9,10,11
0,NVDA,NVIDIA Corporation,183.04,+2.99,+1.66%,155.809M,176.008M,4.449T,37.24,+65.54%,86.62,212.19
1,PLUG,Plug Power Inc.,2.48,+0.25,+11.21%,124.832M,100.523M,3.451B,--,+50.30%,0.69,4.58
2,ONDS,Ondas Inc.,10.51,+0.49,+4.89%,96.532M,92.64M,4.73B,--,"+1,205.59%",0.57,15.28
3,INTC,Intel Corporation,45.58,+2.48,+5.75%,84.551M,101.517M,227.68B,--,+119.66%,17.67,54.60
4,NOK,Nokia Oyj,8.15,+0.08,+0.99%,68.544M,35.129M,45.498B,62.09,+57.95%,4.00,8.37
...,...,...,...,...,...,...,...,...,...,...,...,...
323,SBSW,Sibanye Stillwater Limited,15.10,+0.15,+1.00%,5.065M,7.502M,10.923B,--,+303.74%,3.18,21.29
324,MRK,"Merck & Co., Inc.",120.28,+0.45,+0.38%,5.055M,13.217M,297.379B,16.68,+27.96%,73.31,125.14
325,MCHP,Microchip Technology Incorporated,69.90,-1.49,-2.09%,5.044M,8.814M,37.825B,--,+19.98%,34.13,83.35
326,CRBG,"Corebridge Financial, Inc.",26.45,+1.35,+5.38%,5.036M,5.054M,13.341B,--,-17.52%,23.69,36.57
327,FRO,Frontline plc,36.28,-0.86,-2.32%,5.012M,3.364M,8.077B,23.27,+124.09%,12.40,39.89

In [90]:
thead=table.find('thead')

In [91]:
thead

<thead class="yf-1tpeyy7"><tr class="yf-1tpeyy7"> <th class="[&amp;_.symbol]:tw-text-md yf-1tpeyy7 so lpin shad" data-testid-header="ticker"><div class="colCont yf-1tpeyy7"> Symbol </div> </th> <th class="leftAlignHeader companyName yf-1tpeyy7 so" data-testid-header="companyshortname.raw"><div class="colCont yf-1tpeyy7"> Name </div> </th> <th class="yf-1tpeyy7" data-testid-header="sparkline"><div class="colCont yf-1tpeyy7"> <span data-svelte-h="svelte-1uypmr0"> </span> </div> </th> <th class="yf-1tpeyy7 so" data-testid-header="intradayprice"><div class="colCont yf-1tpeyy7"> <div class="container yf-1d5e06g"><span>Price</span> </div> </div> </th> <th class="yf-1tpeyy7 so" data-testid-header="intradaypricechange"><div class="colCont yf-1tpeyy7"> Change </div> </th> <th class="yf-1tpeyy7 so" data-testid-header="percentchange"><div class="colCont yf-1tpeyy7"> Change % </div> </th> <th class="yf-1tpeyy7 so sorted" data-testid-header="dayvolume"><div class="colCont yf-1tpeyy7"><div aria-hidden="true" class="icon fin-icon inherit-icn sz-medium yf-15ilbqr"><!-- HTML_TAG_START --><svg viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M16.59 8.59 12 13.17 7.41 8.59 6 10l6 6 6-6z"></path></svg><!-- HTML_TAG_END --> </div> Volume </div> </th> <th class="yf-1tpeyy7 so" data-testid-header="avgdailyvol3m"><div class="colCont yf-1tpeyy7"> Avg Vol (3M) </div> </th> <th class="yf-1tpeyy7 so" data-testid-header="intradaymarketcap"><div class="colCont yf-1tpeyy7"> Market Cap </div> </th> <th class="yf-1tpeyy7 so" data-testid-header="peratio.lasttwelvemonths"><div class="colCont yf-1tpeyy7"> <div class="yf-10yevti"><span>P/E Ratio </span><span>(TTM) </span> </div> </div> </th> <th class="yf-1tpeyy7 so" data-testid-header="fiftytwowkpercentchange"><div class="colCont yf-1tpeyy7"> <div class="yf-10yevti"><span>52 Wk </span><span>Change % </span> </div> </div> </th> <th class="yf-1tpeyy7" data-testid-header="fiftyTwoWeekRange"><div class="colCont yf-1tpeyy7"> 52 Wk Range </div> </th> </tr></thead>

In [101]:
header_list=[]
for i in(thead.find_all('tr')[0].find_all('th')):
    
    print(i.text.strip())
    print()
    header_list.append(i.text.strip())

Symbol

Name



Price

Change

Change %

Volume

Avg Vol (3M)

Market Cap

P/E Ratio (TTM)

52 Wk Change %

52 Wk Range

In [97]:
len(thead.find_all('tr'))

1

In [102]:
header_list

['Symbol',
 'Name',
 '',
 'Price',
 'Change',
 'Change %',
 'Volume',
 'Avg Vol (3M)',
 'Market Cap',
 'P/E Ratio (TTM)',
 '52 Wk Change %',
 '52 Wk Range']

In [103]:
header_list.pop(2)

''

In [104]:
header_list.pop(-1)

'52 Wk Range'

In [106]:
header_list.extend(["52 Wk Min","52 Wk Max"])

In [107]:
header_list

['Symbol',
 'Name',
 'Price',
 'Change',
 'Change %',
 'Volume',
 'Avg Vol (3M)',
 'Market Cap',
 'P/E Ratio (TTM)',
 '52 Wk Change %',
 '52 Wk Min',
 '52 Wk Max']

In [108]:
df=pd.DataFrame(twoD)

In [109]:
df

,0,1,2,3,4,5,6,7,8,9,10,11
0,NVDA,NVIDIA Corporation,183.04,+2.99,+1.66%,155.809M,176.008M,4.449T,37.24,+65.54%,86.62,212.19
1,PLUG,Plug Power Inc.,2.48,+0.25,+11.21%,124.832M,100.523M,3.451B,--,+50.30%,0.69,4.58
2,ONDS,Ondas Inc.,10.51,+0.49,+4.89%,96.532M,92.64M,4.73B,--,"+1,205.59%",0.57,15.28
3,INTC,Intel Corporation,45.58,+2.48,+5.75%,84.551M,101.517M,227.68B,--,+119.66%,17.67,54.60
4,NOK,Nokia Oyj,8.15,+0.08,+0.99%,68.544M,35.129M,45.498B,62.09,+57.95%,4.00,8.37
...,...,...,...,...,...,...,...,...,...,...,...,...
323,SBSW,Sibanye Stillwater Limited,15.10,+0.15,+1.00%,5.065M,7.502M,10.923B,--,+303.74%,3.18,21.29
324,MRK,"Merck & Co., Inc.",120.28,+0.45,+0.38%,5.055M,13.217M,297.379B,16.68,+27.96%,73.31,125.14
325,MCHP,Microchip Technology Incorporated,69.90,-1.49,-2.09%,5.044M,8.814M,37.825B,--,+19.98%,34.13,83.35
326,CRBG,"Corebridge Financial, Inc.",26.45,+1.35,+5.38%,5.036M,5.054M,13.341B,--,-17.52%,23.69,36.57
327,FRO,Frontline plc,36.28,-0.86,-2.32%,5.012M,3.364M,8.077B,23.27,+124.09%,12.40,39.89

In [110]:
df.columns = header_list

In [111]:
df

,Symbol,Name,Price,Change,Change %,Volume,Avg Vol (3M),Market Cap,P/E Ratio (TTM),52 Wk Change %,52 Wk Min,52 Wk Max
0,NVDA,NVIDIA Corporation,183.04,+2.99,+1.66%,155.809M,176.008M,4.449T,37.24,+65.54%,86.62,212.19
1,PLUG,Plug Power Inc.,2.48,+0.25,+11.21%,124.832M,100.523M,3.451B,--,+50.30%,0.69,4.58
2,ONDS,Ondas Inc.,10.51,+0.49,+4.89%,96.532M,92.64M,4.73B,--,"+1,205.59%",0.57,15.28
3,INTC,Intel Corporation,45.58,+2.48,+5.75%,84.551M,101.517M,227.68B,--,+119.66%,17.67,54.60
4,NOK,Nokia Oyj,8.15,+0.08,+0.99%,68.544M,35.129M,45.498B,62.09,+57.95%,4.00,8.37
...,...,...,...,...,...,...,...,...,...,...,...,...
323,SBSW,Sibanye Stillwater Limited,15.10,+0.15,+1.00%,5.065M,7.502M,10.923B,--,+303.74%,3.18,21.29
324,MRK,"Merck & Co., Inc.",120.28,+0.45,+0.38%,5.055M,13.217M,297.379B,16.68,+27.96%,73.31,125.14
325,MCHP,Microchip Technology Incorporated,69.90,-1.49,-2.09%,5.044M,8.814M,37.825B,--,+19.98%,34.13,83.35
326,CRBG,"Corebridge Financial, Inc.",26.45,+1.35,+5.38%,5.036M,5.054M,13.341B,--,-17.52%,23.69,36.57
327,FRO,Frontline plc,36.28,-0.86,-2.32%,5.012M,3.364M,8.077B,23.27,+124.09%,12.40,39.89

NVDA
PLUG
ONDS
INTC
NOK
F
AAL
TSLA
MARA
SOFI
BMNR
NU
PLTR
NIO
BBD
AMZN
NFLX
GRAB
KVUE
VALE
VG
HOOD
AMD
WBD
PATH
RIG
IREN
SNAP
MSTR
ITUB
MSFT
MU
T
IBRX
CRGY
OWL
NCLH
RKT
SMCI
CMCSA
EOSE
HBAN
BAC
OPEN
AAPL
COIN
PFE
NVO
ACHR
CRWV
BULL
RIVN
PINS
WULF
GTLB
DNN
SAN
AVGO
CRCL
GOOGL
RGTI
CLSK
MRNA
CIFR
CPNG
AGNC
CCL
TTD
RIOT
LYFT
VZ
ASTS
AES
SOUN
PBR
HIMS
AUR
BTE
INFY
BTG
SLB
QBTS
DKNG
SMR
BF-B
ABEV
WMT
PCG
JD
APLD
RKLB
NOW
LYG
IONQ
WIT
ORCL
GGB
CDE
RUN
CSCO
UBER
SNDK
PR
GOOG
U
FCX
HL
XOM
AG
AA
QS
CLF
JOBY
KO
STLA
BABA
NKE
KHC
OXY
WFC
CVE
DOW
BSX
CPB
PYPL
HAL
CHWY
NVTS
PSKY
RITM
KEY
NBIS
SE
UUUU
UAA
GLW
SHOP
NGD
AXTI
EXC
HPQ
CPRT
FIG
SSRM
DVN
BBWI
ET
PSLV
TOST
MRVL
UWMC
ADT
MOS
UPS
AAOI
STM
CRM
TSM
COHR
BTSG
ASX
CORZ
BE
BMY
ROIV
USAR
BKR
OSCR
CCC
TEVA
FSLY
APH
DAL
ZETA
CVX
M
C
KMI
XYZ
CELH
KDP
WDC
NRG
CMG
CAG
HST
PTEN
PBR-A
COMP
RF
LRCX
GLXY
CFLT
B
STNE
BCS
ONON
MO
MDLZ
CRWD
AEO
APP
HPE
META
DIS
PANW
TGT
CNQ
CRDO
AVTR
WBS
PL
COP
FSK
LITE
ON
QXO
QCOM
INVH
KKR
LYB
DELL
BAX
VNET
ARCC
ZM
BP
FAST
DHT
ADMA
BX
PPL
NEE
GIS
S
EQX
LUMN
ACI
KR
VTRS
PEP
EQT
FRMI
HLN
FNB
KGC
GAP
CNH
LUV
UAL
LUNR
BOX
CSX
AFRM
PG
JPM
ERIC
OBDC
UNH
UEC
EXK
TEAM
NEM
APA
WIX
PBF
GM
VLY
FTNT
PHYS
VISN
XPEV
BB
AR
MNST
SCHW
CX
MAT
HOG
EQNR
TU
AMAT
ANET
MDT
OCUL
ROST
NLY
SONY
RBLX
O
GPK
SLM
PRMB
ASB
TMUS
NOV
FOLD
SM
FIGR
PAGS
SKM
FISV
GEN
HDB
OKLO
DT
TEM
SHEL
GT
CVS
DOC
VSNT
IP
USB
VICI
KLAR
DDOG
TFC
FOXA
NWG
OKTA
VNOM
UMC
SBSW
MRK
MCHP
CRBG
FRO

In [162]:
symbol='PLUG'
headers2=headers = {
    "Cache-Control": "no-cache",
    "Pragma": "no-cache",
    "User-Agent": "Mozilla/5.0"
}
webpage2=requests.get('https://finance.yahoo.com/quote/PLUG/',headers=headers2).text
soup2=BeautifulSoup(webpage2,'lxml')

In [118]:
len(soup.find_all('ul',class_='yf-6myrf1'))

1

In [163]:
float(((soup2.find_all('ul',class_='yf-6myrf1')[0].find_all('li'))[1].text.split()[1]))

2.25

In [143]:
soup.find_all('ul',class_='yf-6myrf1')[0].find_all('li')[0]

<li class="yf-6myrf1"><span class="label yf-6myrf1" title="Previous Close">Previous Close </span> <span class="value yf-6myrf1"><fin-streamer active="" class="yf-6myrf1" data-field="regularMarketPreviousClose" data-trend="none" data-value="2.2300">2.2300 </fin-streamer></span> </li>

In [152]:
 len(soup.find_all('div',attrs={"data-testid": "quote-statistics"}))

1

In [159]:
div_wrapping_table=soup.find_all('div',attrs={"data-testid": "quote-statistics"})[0]

In [161]:
div_wrapping_table.text

" Previous Close  2.2300   Open  2.2500   Bid  2.4400 x 92800  Ask  2.5100 x 92800  Day's Range  2.2400 - 2.5000   52 Week Range  0.6900 - 4.5800   Volume  127,693,218   Avg. Volume  99,926,262   Market Cap (intraday)  3.451B   Beta (5Y Monthly)  2.01  PE Ratio (TTM)  --   EPS (TTM)  -2.3800   Earnings Date (est.)  May 11, 2026  Forward Dividend & Yield  --  Ex-Dividend Date  --  1y Target Est  2.75   "

In [165]:
import requests

url = "https://query1.finance.yahoo.com/v7/finance/quote?symbols=PLUG"
response = requests.get(url)
print(response)
data=response.json()
result = data['quoteResponse']['result'][0]

print("Open:", result['regularMarketOpen'])
print("Previous Close:", result['regularMarketPreviousClose'])
print("Volume:", result['regularMarketVolume'])
print("Market Cap:", result['marketCap'])

<Response [429]>

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [169]:
import yfinance as yf

ticker = yf.Ticker("NVDA")

data = ticker.info
print("Open:", data["open"])
print("Previous Close:", data["previousClose"])

Open: 181.17
Previous Close: 183.04

In [167]:
import sys
!{sys.executable} -m pip install yfinance

Defaulting to user installation because normal site-packages is not writeable

  DEPRECATION: Building 'multitasking' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'multitasking'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  WARNING: The script pwiz.exe is installed in 'C:\Users\Swapnil Sengupta\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script websockets.exe is installed in 'C:\Users\Swapnil Sengupta\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script sample.exe is installed in 'C:\Users\Swapnil Sengupta\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

Collecting yfinance
  Downloading yfinance-1.2.0-py2.py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\swapnil sengupta\appdata\roaming\python\python313\site-packages (from yfinance) (3.0.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\swapnil sengupta\appdata\roaming\python\python313\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: requests>=2.31 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.32.3)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.12.tar.gz (19 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: platformdirs>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.0.1-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Collecting curl_cffi<0.14,>=0.7 (from yfinance)
  Downloading curl_cffi-0.13.0-cp39-abi3-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: protobuf>=3.19.0 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (5.29.3)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-16.0-cp313-cp313-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: cffi>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\programdata\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.4.26)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.3.0)
Downloading yfinance-1.2.0-py2.py3-none-any.whl (130 kB)
Downloading curl_cffi-0.13.0-cp39-abi3-win_amd64.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 1.6/1.6 MB 8.0 MB/s eta 0:00:00
Downloading peewee-4.0.1-py3-none-any.whl (139 kB)
Downloading websockets-16.0-cp313-cp313-win_amd64.whl (178 kB)
Building wheels for collected packages: multitasking
  Building wheel for multitasking (setup.py): started
  Building wheel for multitasking (setup.py): finished with status 'done'
  Created wheel for multitasking: filename=multitasking-0.0.12-py3-none-any.whl size=15618 sha256=d7d1d483ef65c411a3d3ccfad4578588c4788e32374fb7f97d4ddfa5afaed892
  Stored in directory: c:\users\swapnil sengupta\appdata\local\pip\cache\wheels\1e\df\0f\e2bbb22d689b30c681feb5410ab64a2523437b34c8ecfc6476
Successfully built multitasking
Installing collected packages: peewee, multitasking, websockets, curl_cffi, yfinance

   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   -------- ------------------------------- 1/5 [multitasking]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   ---------------------------------------- 5/5 [yfinance]

Successfully installed curl_cffi-0.13.0 multitasking-0.0.12 peewee-4.0.1 websockets-16.0 yfinance-1.2.0

In [172]:
open_data=[]
for index, row in df.iterrows():
    symbol=row['Symbol']
    ticker = yf.Ticker(symbol)

    data = ticker.info
    open=data["open"]
    open_data.append(open)

2

In [174]:
len(open_data)

328

In [175]:
df["Opening Price(5th March)"]=open_data

In [176]:
df

,Symbol,Name,Price,Change,Change %,Volume,Avg Vol (3M),Market Cap,P/E Ratio (TTM),52 Wk Change %,52 Wk Min,52 Wk Max,Opening Price(5th March)
0,NVDA,NVIDIA Corporation,183.04,+2.99,+1.66%,155.809M,176.008M,4.449T,37.24,+65.54%,86.62,212.19,181.170
1,PLUG,Plug Power Inc.,2.48,+0.25,+11.21%,124.832M,100.523M,3.451B,--,+50.30%,0.69,4.58,2.435
2,ONDS,Ondas Inc.,10.51,+0.49,+4.89%,96.532M,92.64M,4.73B,--,"+1,205.59%",0.57,15.28,10.500
3,INTC,Intel Corporation,45.58,+2.48,+5.75%,84.551M,101.517M,227.68B,--,+119.66%,17.67,54.60,44.870
4,NOK,Nokia Oyj,8.15,+0.08,+0.99%,68.544M,35.129M,45.498B,62.09,+57.95%,4.00,8.37,7.940
...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,SBSW,Sibanye Stillwater Limited,15.10,+0.15,+1.00%,5.065M,7.502M,10.923B,--,+303.74%,3.18,21.29,14.500
324,MRK,"Merck & Co., Inc.",120.28,+0.45,+0.38%,5.055M,13.217M,297.379B,16.68,+27.96%,73.31,125.14,119.110
325,MCHP,Microchip Technology Incorporated,69.90,-1.49,-2.09%,5.044M,8.814M,37.825B,--,+19.98%,34.13,83.35,69.030
326,CRBG,"Corebridge Financial, Inc.",26.45,+1.35,+5.38%,5.036M,5.054M,13.341B,--,-17.52%,23.69,36.57,26.260
327,FRO,Frontline plc,36.28,-0.86,-2.32%,5.012M,3.364M,8.077B,23.27,+124.09%,12.40,39.89,35.190

In [177]:
df = df.rename(columns={"Price": "Price(Before Opening on 5th March)"})

In [178]:
df

,Symbol,Name,Price(Before Opening on 5th March),Change,Change %,Volume,Avg Vol (3M),Market Cap,P/E Ratio (TTM),52 Wk Change %,52 Wk Min,52 Wk Max,Opening Price(5th March)
0,NVDA,NVIDIA Corporation,183.04,+2.99,+1.66%,155.809M,176.008M,4.449T,37.24,+65.54%,86.62,212.19,181.170
1,PLUG,Plug Power Inc.,2.48,+0.25,+11.21%,124.832M,100.523M,3.451B,--,+50.30%,0.69,4.58,2.435
2,ONDS,Ondas Inc.,10.51,+0.49,+4.89%,96.532M,92.64M,4.73B,--,"+1,205.59%",0.57,15.28,10.500
3,INTC,Intel Corporation,45.58,+2.48,+5.75%,84.551M,101.517M,227.68B,--,+119.66%,17.67,54.60,44.870
4,NOK,Nokia Oyj,8.15,+0.08,+0.99%,68.544M,35.129M,45.498B,62.09,+57.95%,4.00,8.37,7.940
...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,SBSW,Sibanye Stillwater Limited,15.10,+0.15,+1.00%,5.065M,7.502M,10.923B,--,+303.74%,3.18,21.29,14.500
324,MRK,"Merck & Co., Inc.",120.28,+0.45,+0.38%,5.055M,13.217M,297.379B,16.68,+27.96%,73.31,125.14,119.110
325,MCHP,Microchip Technology Incorporated,69.90,-1.49,-2.09%,5.044M,8.814M,37.825B,--,+19.98%,34.13,83.35,69.030
326,CRBG,"Corebridge Financial, Inc.",26.45,+1.35,+5.38%,5.036M,5.054M,13.341B,--,-17.52%,23.69,36.57,26.260
327,FRO,Frontline plc,36.28,-0.86,-2.32%,5.012M,3.364M,8.077B,23.27,+124.09%,12.40,39.89,35.190

In [179]:
df = df.rename(columns={"Change": "Change from Prev Day"})

In [180]:
df

,Symbol,Name,Price(Before Opening on 5th March),Change from Prev Day,Change %,Volume,Avg Vol (3M),Market Cap,P/E Ratio (TTM),52 Wk Change %,52 Wk Min,52 Wk Max,Opening Price(5th March)
0,NVDA,NVIDIA Corporation,183.04,+2.99,+1.66%,155.809M,176.008M,4.449T,37.24,+65.54%,86.62,212.19,181.170
1,PLUG,Plug Power Inc.,2.48,+0.25,+11.21%,124.832M,100.523M,3.451B,--,+50.30%,0.69,4.58,2.435
2,ONDS,Ondas Inc.,10.51,+0.49,+4.89%,96.532M,92.64M,4.73B,--,"+1,205.59%",0.57,15.28,10.500
3,INTC,Intel Corporation,45.58,+2.48,+5.75%,84.551M,101.517M,227.68B,--,+119.66%,17.67,54.60,44.870
4,NOK,Nokia Oyj,8.15,+0.08,+0.99%,68.544M,35.129M,45.498B,62.09,+57.95%,4.00,8.37,7.940
...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,SBSW,Sibanye Stillwater Limited,15.10,+0.15,+1.00%,5.065M,7.502M,10.923B,--,+303.74%,3.18,21.29,14.500
324,MRK,"Merck & Co., Inc.",120.28,+0.45,+0.38%,5.055M,13.217M,297.379B,16.68,+27.96%,73.31,125.14,119.110
325,MCHP,Microchip Technology Incorporated,69.90,-1.49,-2.09%,5.044M,8.814M,37.825B,--,+19.98%,34.13,83.35,69.030
326,CRBG,"Corebridge Financial, Inc.",26.45,+1.35,+5.38%,5.036M,5.054M,13.341B,--,-17.52%,23.69,36.57,26.260
327,FRO,Frontline plc,36.28,-0.86,-2.32%,5.012M,3.364M,8.077B,23.27,+124.09%,12.40,39.89,35.190

In [183]:
df.to_csv('stockData_before5thOpening.csv')